"""Admin console — users, quality, enforcement, pricing, licensing, states, reports, training."""

from . import C

SHEET = "04-Admin-Console"
PREFIX = "ADM"

_ADMIN = "Logged in as an admin (user_type_id=3) on the Admin Console"

CASES = [
    # ---- Console home --------------------------------------------------------
    C("Console", "Home", "Admin", "Mobile",
      "The console home shows the KPI header and all ten management tiles",
      _ADMIN,
      "Log in as an admin|Observe the console home",
      "-",
      "Header 'Admin Console' with Users / Active holds / Open reports, and tiles for All Users, Services, Quality Control, Reports, Price Overrides, Enforcements, Training, Store, Licenses, States",
      "P1", "Functional", "Automated", "mobile.admin.AdminConsoleTest#consoleShowsManagementTiles"),
    C("Console", "Home", "Admin", "Mobile",
      "KPI counters match the underlying data",
      "Known counts in the database",
      "Compare the header counters with the DB",
      "-",
      "Total users, active suspensions and open reports match; loading shows '—' rather than 0",
      "P2", "Functional", "Manual", ""),
    C("Console", "Attention", "Admin", "Mobile",
      "Unread notifications produce the attention strip with a category summary",
      "Admin with unread notifications across categories",
      "Open the console home",
      "-",
      "'<n> need(s) attention' with a summary such as '2 pros · 1 licenses'; tapping opens the notification centre",
      "P2", "Functional", "Automated", "mobile.admin.AdminConsoleTest#attentionStripAppearsWhenUnread"),
    C("Console", "Attention", "Admin", "Mobile",
      "Active suspensions with no unread notifications show the suspension banner",
      "≥1 active suspension, no unread notifications",
      "Open the console home",
      "-",
      "'<n> client(s) currently suspended' with a 'Review' action opening Enforcements",
      "P3", "Functional", "Manual", ""),
    C("Console", "Notifications", "Admin", "Mobile",
      "A tapped notification deep-links to its queue",
      "Notifications in the users/licenses/states/store/support categories",
      "Open the notification centre|Tap a notification of each category",
      "-",
      "Each opens its queue (All Users, Licence verification, States, Store vendors, Reports)",
      "P2", "Functional", "Manual", ""),
    C("Console", "Notifications", "Admin", "Mobile",
      "'Mark all read' clears the badge",
      "Admin with unread notifications",
      "Open the notification centre|Tap 'Mark all read'",
      "-",
      "The unread count drops to zero on the bell and on the tiles",
      "P2", "Functional", "Manual", ""),
    C("Console", "Tabs", "Admin", "Mobile",
      "The four console tabs open Dashboard, Pros, Quality and Reports",
      _ADMIN,
      "Tap each bottom-nav tab",
      "-",
      "Each tab renders its screen",
      "P1", "Functional", "Automated", "mobile.admin.AdminConsoleTest#consoleTabsOpen"),
    C("Console", "Session", "Admin", "Mobile",
      "'Log out' from the console ends the admin session",
      _ADMIN,
      "Tap the logout action|Confirm",
      "-",
      "Session cleared and the login screen is shown",
      "P2", "Functional", "Manual", ""),

    # ---- Users ---------------------------------------------------------------
    C("Users", "All Users", "Admin", "Mobile",
      "All Users lists clients and professionals with the right counts",
      _ADMIN,
      "Open the 'All Users' tile",
      "-",
      "Client and professional counts match the console tile subtitle",
      "P1", "Functional", "Automated", "mobile.admin.AdminUsersTest#allUsersOpens"),
    C("Users", "Professional status", "Admin", "Mobile",
      "Professionals are segmented into pending / approved / rejected / incomplete",
      "Professionals in each state",
      "Open the professionals status dashboard|Open each segment",
      "-",
      "Each segment lists only professionals in that state",
      "P1", "Functional", "Automated", "mobile.admin.AdminUsersTest#professionalStatusSegments"),
    C("Users", "Professional detail", "Admin", "Mobile",
      "A professional's documents can be approved",
      "Professional with a submitted document",
      "Open the professional|Open the document|Tap 'Approve'",
      "-",
      "The document is marked approved and the professional moves toward approved status",
      "P1", "Functional", "Manual", ""),
    C("Users", "Professional detail", "Admin", "Mobile",
      "A document can be rejected with a reason shown to the professional",
      "Professional with a submitted document",
      "Open the document|Tap 'Reject'|Enter the optional reason|Confirm",
      "'photo is unreadable'",
      "The rejection and reason are stored and surfaced to the professional as 'Reason: …'",
      "P1", "Functional", "Manual", ""),
    C("Users", "Professional detail", "Admin", "Mobile",
      "The automated DMV/board check result is displayed and can be re-run",
      "Professional with a licence document",
      "Open the document|Review 'Automated check' / 'DMV attribute match'|Tap 'Re-run auto-check'",
      "-",
      "The provider result (or 'Automated check not run') is displayed with the raw response, and re-running updates it",
      "P2", "Functional", "Manual", ""),
    C("Users", "Reviews", "Admin", "Mobile",
      "A professional's reviews are visible with pagination",
      "Professional with many reviews",
      "Open the professional's reviews",
      "-",
      "'Showing <n> of <total>' and further pages load",
      "P3", "Functional", "Manual", ""),

    # ---- Licence verification queue -----------------------------------------
    C("Licensing", "Queue", "Admin", "Mobile",
      "Submitted licences appear in the verification queue",
      "A professional submitted a licence",
      "Open the 'Licenses' tile",
      "-",
      "The submission is listed with the professional, board, number and submission date",
      "P1", "Functional", "Automated", "mobile.admin.AdminUsersTest#automatedCheckResultIsShown"),
    C("Licensing", "Approve", "Admin", "Mobile",
      "Approving a licence makes the professional bookable",
      "Licence pending in the queue",
      "Open the submission|Tap 'Approve'",
      "-",
      "The licence is approved and the professional becomes bookable by clients",
      "P1", "Functional", "Manual", ""),
    C("Licensing", "Reject", "Admin", "Mobile",
      "Rejecting a licence records the shared reason",
      "Licence pending in the queue",
      "Tap 'Reject'|Enter the reason|Confirm 'Reject submission'",
      "'licence expired'",
      "The submission is rejected and the reason is shared with the professional",
      "P1", "Functional", "Manual", ""),
    C("Licensing", "Documents", "Admin", "Mobile",
      "Both sides of the document can be viewed",
      "Submission with front and back images",
      "Tap 'View document' and 'View back of document'",
      "-",
      "Both images open in the viewer",
      "P3", "Functional", "Manual", ""),

    # ---- Quality control -----------------------------------------------------
    C("Quality", "Search", "Admin", "Mobile",
      "Quality control can be searched by email or ID",
      _ADMIN,
      "Open 'Quality Control'|Search by email|Search by ID",
      "trimiotest+verified@gmail.com",
      "The matching user is returned; 'Refresh' reloads the list",
      "P2", "Functional", "Automated", "mobile.admin.AdminQualityTest#searchFindsUser"),
    C("Quality", "Suspend", "Admin", "Mobile",
      "A user can be suspended with a mandatory reason",
      "A target user in the quality list",
      "Open Actions|Tap 'Suspend'|Submit with an empty reason|Enter a reason and submit",
      "'repeated no-shows'",
      "'Reason (required)' blocks an empty submission; with a reason the user is suspended and appears in Enforcements",
      "P1", "Functional", "Manual", ""),
    C("Quality", "Deactivate", "Admin", "Mobile",
      "A user can be deactivated and reactivated",
      "An active user",
      "Tap 'Deactivate'|Confirm 'Are you sure?'|Tap 'Reactivate'",
      "-",
      "The account status flips both ways and login behaviour follows it",
      "P1", "Functional", "Manual", ""),
    C("Quality", "Streaks", "Admin", "Mobile",
      "The streak review screen surfaces repeat-offender patterns",
      "A professional with repeated low ratings",
      "Open the streak review page",
      "-",
      "The streak is listed with the underlying reviews",
      "P3", "Functional", "Manual", ""),

    # ---- Enforcements --------------------------------------------------------
    C("Enforcements", "List", "Admin", "Mobile",
      "Active enforcements are listed with their reasons",
      "≥1 active suspension",
      "Open the 'Enforcements' tile",
      "-",
      "Each entry shows 'Reason: <reason>' and the remaining duration",
      "P1", "Functional", "Automated", "mobile.admin.AdminQueuesTest#enforcementsAreListed"),
    C("Enforcements", "Extend", "Admin", "Mobile",
      "A suspension can be extended by 1–30 days",
      "An active suspension",
      "Tap 'Extend'|Choose a duration|Confirm",
      "7 days",
      "'Choose duration (1–30 days)' enforces the range and the end date shifts by the chosen amount",
      "P2", "Functional", "Manual", ""),
    C("Enforcements", "Reinstate", "Admin", "Mobile",
      "Reinstating a user restores access immediately",
      "A suspended user",
      "Tap 'Reinstate'|Confirm",
      "-",
      "The hold clears, the console counter drops and the user can log in and transact again",
      "P1", "Functional", "Manual", ""),
    C("Enforcements", "Remove", "Admin", "Mobile",
      "An enforcement record can be removed",
      "An enforcement record",
      "Tap 'Remove'|Confirm",
      "-",
      "The record is deleted from the list",
      "P3", "Functional", "Manual", ""),

    # ---- Price overrides -----------------------------------------------------
    C("Pricing", "Create", "Admin", "Mobile",
      "A fixed-price override can be created for a service",
      _ADMIN,
      "Open 'Price Overrides'|Tap 'New'|Choose a service|Set a fixed price|Enter a reason|Save",
      "service X, $45, reason 'promo'",
      "The override is saved and clients booking that service see the overridden price",
      "P1", "Functional", "Automated", "mobile.admin.AdminQueuesTest#overrideCanBeCreated (disabled by default)"),
    C("Pricing", "Create", "Admin", "Mobile",
      "A multiplier override applies proportionally",
      _ADMIN,
      "Create an override with a multiplier instead of a fixed price",
      "×1.25",
      "The client price is the base price × the multiplier",
      "P1", "Functional", "Manual", ""),
    C("Pricing", "Validation", "Admin", "Mobile",
      "Service and reason are mandatory",
      "In the override editor",
      "Save with no service / no reason",
      "-",
      "'Service *' and 'Reason *' block the save",
      "P2", "Negative", "Manual", ""),
    C("Pricing", "Scope", "Admin", "Mobile",
      "Scope by pro level restricts who the override applies to",
      "Professionals at different levels",
      "Create an override scoped to one pro level|Compare prices across levels",
      "level = Any vs specific",
      "Only professionals at the scoped level use the overridden price",
      "P2", "Functional", "Manual", ""),
    C("Pricing", "Effective dates", "Admin", "Mobile",
      "Effective from/to bound when the override applies",
      "-",
      "Create an override effective only in the future|Book today|Wait for the window",
      "from tomorrow",
      "The override does not apply outside its window",
      "P2", "Functional", "Manual", ""),
    C("Pricing", "Delete", "Admin", "Mobile",
      "An override can be deleted after confirmation",
      "An existing override",
      "Tap 'Delete'|Confirm 'Delete override?'",
      "-",
      "The override is removed and prices revert to base",
      "P2", "Functional", "Manual", ""),

    # ---- Reports -------------------------------------------------------------
    C("Reports", "Queue", "Admin", "Mobile",
      "Open support reports are listed and the count matches the console tile",
      "≥1 open report",
      "Open the 'Reports' tile",
      "-",
      "Open (non resolved/closed) reports are listed; the count matches '<n> open'",
      "P1", "Functional", "Automated", "mobile.admin.AdminQueuesTest#openReportsAreListed"),
    C("Reports", "Detail", "Admin", "Mobile",
      "A report can be opened, actioned and resolved",
      "An open report",
      "Open the report|Respond|Mark it resolved",
      "-",
      "The status changes to resolved, the count drops and the client sees the response",
      "P1", "Functional", "Manual", ""),
    C("Reports", "Refunds", "Support", "Mobile",
      "A refund request can be processed or cancelled from the support console",
      "Logged in as support with a pending refund request",
      "Open 'All Refund Requests'|Tap 'REFUND' on one|Tap 'CANCEL' on another",
      "-",
      "'Refund processed' / 'Request canceled' and the money movement matches",
      "P1", "Functional", "Manual", ""),

    # ---- Services ------------------------------------------------------------
    C("Services", "Catalogue", "Admin", "Mobile",
      "The services catalogue lists every service and matches the tile count",
      _ADMIN,
      "Open the 'Services' tile",
      "-",
      "All services are listed and the count matches the console tile",
      "P2", "Functional", "Automated", "mobile.admin.AdminQueuesTest#servicesAreListed"),

    # ---- Training ------------------------------------------------------------
    C("Training", "Create", "Admin", "Mobile",
      "A training material can be created",
      _ADMIN,
      "Open 'Training'|Tap 'New'|Enter title, type and file URL|Save",
      "video, https://…/intro.mp4",
      "The material is created and appears to professionals",
      "P2", "Functional", "Automated", "mobile.admin.AdminQueuesTest#materialCanBeCreated (disabled by default)"),
    C("Training", "Validation", "Admin", "Mobile",
      "Title and file URL are mandatory; duration must be a whole number",
      "In the new-material dialog",
      "Save without a title/URL|Enter a fractional duration",
      "duration = 1.5",
      "'Title and File URL are required' and 'Duration must be a whole number'",
      "P2", "Negative", "Manual", ""),
    C("Training", "Delete", "Admin", "Mobile",
      "A training material can be deleted after confirmation",
      "An existing material",
      "Tap 'Delete'|Confirm 'Delete material?'",
      "-",
      "The material is removed and no longer offered to professionals",
      "P3", "Functional", "Manual", ""),
    C("Training", "Completion", "Admin", "Mobile",
      "Completion counts reflect professional progress",
      "A professional completed the material",
      "Open the material",
      "-",
      "'Completed by <n> pro(s)' increments",
      "P3", "Functional", "Manual", ""),

    # ---- Countries & states --------------------------------------------------
    C("States", "List", "Admin", "Mobile",
      "States are listed per country with an active count",
      _ADMIN,
      "Open the 'States' / 'Countries & States' destination",
      "-",
      "'<active> of <total> states active'; a country with none shows 'No states for this country.'",
      "P2", "Functional", "Automated", "mobile.admin.AdminQueuesTest#statesAreListed"),
    C("States", "Approve", "Admin", "Mobile",
      "Approving a state makes it part of Trimio",
      "A state pending review",
      "Open the state|Review the law and documents|Tap 'Approve'|Confirm 'Approve <state>?'",
      "-",
      "The state becomes active and professionals there can register/operate",
      "P1", "Functional", "Manual", ""),
    C("States", "Law watch", "Admin", "Mobile",
      "New law-watch alerts are surfaced and can be reviewed or dismissed",
      "A state with new alerts",
      "Open the state|Observe 'Law watch — <n> new'|Tap 'Mark reviewed' / 'Dismiss'",
      "-",
      "The alert count clears and the review is recorded with the admin note",
      "P2", "Functional", "Manual", ""),
    C("States", "Sources", "Admin", "Mobile",
      "Legal sources can be added and removed",
      "On a state detail",
      "Tap 'Add source'|Choose a type and URL|Add|Then 'Remove' and confirm",
      "Statute / Regulation / Board page / Document / Other",
      "The source is added, listed and removable after 'Remove source?' confirmation",
      "P3", "Functional", "Manual", ""),
    C("States", "Re-check", "Admin", "Mobile",
      "'Re-check' refreshes the last-checked timestamp",
      "On a state detail",
      "Tap 'Re-check'",
      "-",
      "'Last checked <date>' updates",
      "P3", "Functional", "Manual", ""),
]
