"""Authentication, onboarding and session — shared by every role (mobile)."""

from . import C

SHEET = "01-Auth-Onboarding"
PREFIX = "AUTH"

_APP = "Trimio app installed; app data cleared (fresh onboarding)"
_LOGIN = "On the Login screen"

CASES = [
    # ---- Onboarding carousel -------------------------------------------------
    C("Onboarding", "Carousel", "Any", "Mobile",
      "First launch lands on the 3-slide onboarding carousel",
      _APP,
      "Launch the Trimio app|Observe the first slide",
      "-",
      "Slide 1 shows the title 'Welcome to Trimio' with its description, plus Skip / Next / Sign in controls",
      "P1", "Functional", "Automated", "mobile.OnboardingTest#carouselLoadsOnFirstSlide"),
    C("Onboarding", "Carousel", "Any", "Mobile",
      "Next advances through all three slides to 'Get started'",
      _APP,
      "Launch the app|Tap 'Next'|Tap 'Next'|Observe the CTA on slide 3",
      "-",
      "Each tap advances one slide; on slide 3 the CTA reads 'Get started'",
      "P2", "Functional", "Automated", "mobile.OnboardingTest#getStartedOpensRolePage"),
    C("Onboarding", "Carousel", "Any", "Mobile",
      "'Skip' jumps straight to the Login screen",
      _APP,
      "Launch the app|Tap 'Skip' (top-right)",
      "-",
      "Login screen opens (login_button present); onboarding is not shown again in this session",
      "P2", "Functional", "Automated", "mobile.OnboardingTest#skipOpensLogin"),
    C("Onboarding", "Carousel", "Any", "Mobile",
      "'Sign in' on the carousel opens the Login screen",
      _APP,
      "Launch the app|Tap 'Sign in' at the bottom",
      "-",
      "Login screen opens",
      "P2", "Functional", "Automated", "mobile.OnboardingTest#signInOpensLogin"),
    C("Onboarding", "Carousel", "Any", "Mobile",
      "'Get started' opens the role-selection page",
      _APP,
      "Launch the app|Tap 'Next' twice|Tap 'Get started'",
      "-",
      "Role page shows the cards \"I'm a Client\" and \"I'm a Professional\"",
      "P1", "Functional", "Automated", "mobile.OnboardingTest#getStartedOpensRolePage"),
    C("Onboarding", "Role selection", "Any", "Mobile",
      "Role page offers only Client and Professional in the signup flow",
      "On the role page via 'Get started'",
      "Inspect the visible role cards",
      "-",
      "Only \"I'm a Client\" and \"I'm a Professional\" are offered; \"I'm an Admin\" is not present (reset flow only)",
      "P2", "Functional", "Automated", "mobile.OnboardingTest#getStartedOpensRolePage"),
    C("Onboarding", "Role selection", "Client", "Mobile",
      "Choosing 'I'm a Client' opens the client registration form",
      "On the role page",
      "Tap \"I'm a Client\"",
      "-",
      "Registration form opens with header 'Create your account'",
      "P1", "Functional", "Automated", "mobile.RegistrationTest (setup)"),
    C("Onboarding", "Role selection", "Professional", "Mobile",
      "Choosing \"I'm a Professional\" opens the professional registration form",
      "On the role page",
      "Tap \"I'm a Professional\"",
      "-",
      "Registration form opens for the professional role",
      "P1", "Functional", "Manual", ""),
    C("Onboarding", "Privacy", "Any", "Mobile",
      "Privacy Policy document opens from onboarding",
      _APP,
      "Open the Privacy Policy link|Wait for the document to render",
      "-",
      "'Privacy Policy' screen renders the document; no 'Failed to load privacy policy' error",
      "P3", "Functional", "Manual", ""),

    # ---- Registration --------------------------------------------------------
    C("Registration", "Happy path", "Client", "Mobile",
      "A new client registers successfully with valid data",
      "On the client registration form",
      "Enter a unique email|Enter a 10-digit phone|Enter a policy-compliant password|Tick the Terms checkbox|Tap 'Create account'",
      "trimiotest+client<ts>@gmail.com / 5551234567 / Trimio@2580",
      "Account is created in Postgres + Firebase and the app advances past the form",
      "P1", "Functional", "Automated", "mobile.RegistrationTest#registerNewClientSucceeds"),
    C("Registration", "Validation", "Client", "Mobile",
      "Empty email is rejected",
      "On the registration form",
      "Leave email blank|Fill the other fields|Submit",
      "email = ''",
      "Validation message 'Please enter your email'",
      "P2", "Negative", "Automated", "mobile.RegistrationTest#invalidRegistrationIsRejected"),
    C("Registration", "Validation", "Client", "Mobile",
      "Malformed email is rejected client-side",
      "On the registration form",
      "Enter 'not-an-email'|Fill the other fields|Submit",
      "email = not-an-email",
      "Validation message 'Please enter a valid email address'",
      "P2", "Negative", "Automated", "mobile.RegistrationTest#invalidRegistrationIsRejected"),
    C("Registration", "Validation", "Client", "Mobile",
      "Empty phone number is rejected",
      "On the registration form",
      "Leave phone blank|Fill the other fields|Submit",
      "phone = ''",
      "Validation message 'Please enter your phone number'",
      "P2", "Negative", "Automated", "mobile.RegistrationTest#invalidRegistrationIsRejected"),
    C("Registration", "Validation", "Client", "Mobile",
      "Phone shorter than 10 digits is rejected",
      "On the registration form",
      "Enter a 9-digit phone|Fill the other fields|Submit",
      "phone = 555123456",
      "Validation message 'Phone number must be 10 digits'",
      "P2", "Negative", "Automated", "mobile.RegistrationTest#invalidRegistrationIsRejected"),
    C("Registration", "Password policy", "Client", "Mobile",
      "Password under 8 characters is rejected",
      "On the registration form",
      "Enter 'Ab@1'|Fill the other fields|Submit",
      "password = Ab@1",
      "Validation message '…at least 8 characters long'",
      "P2", "Negative", "Automated", "mobile.RegistrationTest#invalidRegistrationIsRejected"),
    C("Registration", "Password policy", "Client", "Mobile",
      "Password without an uppercase letter is rejected",
      "On the registration form",
      "Enter 'trimio@2580'|Submit",
      "password = trimio@2580",
      "Validation message about a required uppercase character",
      "P2", "Negative", "Automated", "mobile.RegistrationTest#invalidRegistrationIsRejected"),
    C("Registration", "Password policy", "Client", "Mobile",
      "Password without a digit / special character is rejected",
      "On the registration form",
      "Enter 'Trimiopass'|Submit",
      "password = Trimiopass",
      "Validation messages about a required digit and special character",
      "P2", "Negative", "Automated", "mobile.RegistrationTest#invalidRegistrationIsRejected"),
    C("Registration", "Password policy", "Client", "Mobile",
      "Password containing a sequential run (123 / 234) is rejected",
      "On the registration form",
      "Enter 'Trimio@1234'|Submit",
      "password = Trimio@1234",
      "Validation message \"Password cannot contain sequential numbers like '123'\"",
      "P2", "Negative", "Automated", "mobile.RegistrationTest#invalidRegistrationIsRejected"),
    C("Registration", "Terms", "Client", "Mobile",
      "Submitting without accepting the Terms is blocked",
      "On the registration form with all fields valid",
      "Fill all fields|Leave the Terms checkbox unticked|Tap 'Create account'",
      "valid data, terms unchecked",
      "Message \"Please accept Trimio's Terms and Privacy Policy to continue.\" (curly apostrophe) and no account is created",
      "P1", "Negative", "Automated", "mobile.RegistrationTest#unacceptedTermsIsRejected"),
    C("Registration", "Duplicate", "Client", "Mobile",
      "Registering an already-registered email is rejected",
      "An account already exists for the email",
      "Enter the existing email|Fill the other fields|Submit",
      "existing verified account email",
      "Backend rejects the signup; a duplicate/exists error is surfaced and no second account is created",
      "P1", "Negative", "Automated", "mobile.RegistrationTest#duplicateEmailIsRejected"),
    C("Registration", "Keyboard", "Client", "Mobile",
      "Terms checkbox and submit remain reachable with the keyboard open",
      "On the registration form",
      "Focus the password field so the keyboard opens|Attempt to tick Terms and submit",
      "-",
      "The keyboard is dismissed (or the form scrolls) so both controls stay tappable — regression guard for the off-screen-semantics bug",
      "P2", "Regression", "Automated", "MobileBasePage#hideKeyboard (used by RegistrationScreen)"),

    # ---- Login ---------------------------------------------------------------
    C("Login", "Happy path", "Client", "Mobile",
      "A verified client logs in and lands on the client home tabs",
      "A verified client account exists",
      "Open Login|Enter valid email and password|Tap login",
      "trimiotest+verified@gmail.com / Trimio@1234",
      "Login accepted, session persisted, client bottom nav (Home/Book/Appointments/Shop/Profile) is shown",
      "P1", "Functional", "Automated", "mobile.LoginTest#validCredentialsAreAccepted"),
    C("Login", "Happy path", "Professional", "Mobile",
      "A professional logs in and lands on the professional dashboard",
      "An approved professional account exists",
      "Open Login|Enter professional credentials|Tap login",
      "professional account",
      "Professional bottom nav (DashBoard/My Bookings/Client Hub/Store/Account) is shown",
      "P1", "Functional", "Automated", "mobile.professional.ProfessionalDashboardTest#professionalLandsOnDashboard"),
    C("Login", "Happy path", "Professional", "Mobile",
      "A professional with a pending profile is routed to the 'profile not created' screen",
      "A professional account whose profile is empty or approval_status='pending'",
      "Log in as that professional",
      "pending professional account",
      "ProfessionalNotCreatedHomePage is shown instead of the dashboard tabs",
      "P2", "Functional", "Manual", ""),
    C("Login", "Happy path", "Admin", "Mobile",
      "An admin logs in and lands on the Admin Console",
      "An admin account (user_type_id=3) exists",
      "Log in as admin",
      "admin account",
      "Admin Console with the Dashboard/Pros/Quality/Reports tabs is shown",
      "P1", "Functional", "Automated", "mobile.admin.AdminConsoleTest#adminLandsOnConsole"),
    C("Login", "Happy path", "Vendor", "Mobile",
      "A vendor logs in and lands on the vendor home page",
      "A vendor account (user_type_id=9) exists",
      "Log in as vendor",
      "vendor account",
      "Vendor home with Overview/Catalog/Orders/Payouts is shown",
      "P2", "Functional", "Manual", ""),
    C("Login", "Validation", "Any", "Mobile",
      "Empty email is rejected",
      _LOGIN,
      "Leave email blank|Enter a password|Submit",
      "email = ''",
      "'Please enter your email' and the user stays on the form",
      "P2", "Negative", "Automated", "mobile.LoginTest#invalidLoginIsRejected"),
    C("Login", "Validation", "Any", "Mobile",
      "Malformed email is rejected",
      _LOGIN,
      "Enter 'bad-email'|Enter a password|Submit",
      "email = bad-email",
      "'Please enter a valid email address'",
      "P2", "Negative", "Automated", "mobile.LoginTest#invalidLoginIsRejected"),
    C("Login", "Validation", "Any", "Mobile",
      "Empty password is rejected",
      _LOGIN,
      "Enter a valid email|Leave password blank|Submit",
      "password = ''",
      "'Please enter your password'",
      "P2", "Negative", "Automated", "mobile.LoginTest#invalidLoginIsRejected"),
    C("Login", "Validation", "Any", "Mobile",
      "Login no longer enforces a minimum password length",
      _LOGIN,
      "Enter a valid email|Enter a 3-character password|Submit",
      "password = 'abc'",
      "No client-side length error; the request reaches the backend and fails with 'Invalid email or password.'",
      "P3", "Regression", "Automated", "mobile.LoginTest#invalidLoginIsRejected"),
    C("Login", "Backend", "Any", "Mobile",
      "Unknown email is rejected by the backend",
      _LOGIN,
      "Enter an unregistered email and any password|Submit",
      "nobody+<ts>@gmail.com",
      "Snackbar 'Invalid email or password.' and the user stays on the form",
      "P1", "Negative", "Automated", "mobile.LoginTest#invalidLoginIsRejected"),
    C("Login", "Backend", "Any", "Mobile",
      "Correct email with the wrong password is rejected",
      "A registered account exists",
      "Enter the registered email with a wrong password|Submit",
      "verified email / Wrong@9876",
      "Snackbar 'Invalid email or password.'",
      "P1", "Negative", "Automated", "mobile.LoginTest#invalidLoginIsRejected"),
    C("Login", "Security", "Any", "Mobile",
      "Password field masks input and the visibility toggle reveals it",
      _LOGIN,
      "Type a password|Observe masking|Tap the visibility toggle",
      "any password",
      "Input is masked by default and revealed only while the toggle is on",
      "P3", "Security", "Manual", ""),
    C("Login", "Biometrics", "Any", "Mobile",
      "'Faster sign-in' biometric opt-in can be enabled and declined",
      "Device has biometrics enrolled; first successful login",
      "Log in|On the 'Faster sign-in' prompt tap 'Not now'|Log out and log in again|Tap 'Enable'",
      "-",
      "'Not now' dismisses without enabling; 'Enable' registers biometric login and subsequent launches offer it",
      "P3", "Functional", "Manual", ""),
    C("Login", "Navigation", "Any", "Mobile",
      "'Forgot password?' opens the password-reset role page",
      _LOGIN,
      "Tap 'Forgot password?'",
      "-",
      "Role page opens in reset mode, including \"I'm an Admin\"",
      "P2", "Functional", "Automated", "mobile.ForgotPasswordTest (setup)"),
    C("Login", "Navigation", "Any", "Mobile",
      "'Register' from the login screen returns to signup",
      _LOGIN,
      "Tap 'Register'",
      "-",
      "The role/registration flow opens",
      "P3", "Functional", "Manual", ""),
    C("Login", "Navigation", "Vendor", "Mobile",
      "'Want to sell on Trimio? Apply to sell' opens the vendor application",
      _LOGIN,
      "Tap 'Apply to sell'",
      "-",
      "'Sell on Trimio' application page opens",
      "P2", "Functional", "Automated", "web.VendorApplyTest#applyEntryPointOpensForm"),
    C("Login", "Session", "Any", "Mobile",
      "A persisted session skips the login screen on relaunch",
      "Logged in previously without logging out",
      "Kill and relaunch the app",
      "-",
      "The app restores the session and routes straight to the role's landing screen",
      "P2", "Functional", "Manual", ""),
    C("Login", "Session", "Any", "Mobile",
      "Logging out clears the session and returns to login",
      "Logged in",
      "Open the account menu|Tap 'Log out'|Confirm",
      "-",
      "Prefs (userId/userType/…) are cleared and the login screen is shown; relaunch does not restore the session",
      "P1", "Functional", "Manual", ""),

    # ---- Forgot password -----------------------------------------------------
    C("Forgot Password", "Validation", "Any", "Mobile",
      "Submitting with both fields empty is rejected",
      "On the forgot-password form",
      "Leave email and phone blank|Tap 'Send reset code'",
      "-",
      "Snackbar 'Please enter your email or phone number.'",
      "P2", "Negative", "Automated", "mobile.ForgotPasswordTest#invalidResetRequestIsRejected"),
    C("Forgot Password", "Validation", "Any", "Mobile",
      "Supplying both email and phone is rejected",
      "On the forgot-password form",
      "Enter both an email and a phone|Submit",
      "email + phone",
      "Snackbar 'Please enter either an email OR a phone number, not both.'",
      "P2", "Negative", "Automated", "mobile.ForgotPasswordTest#invalidResetRequestIsRejected"),
    C("Forgot Password", "Validation", "Any", "Mobile",
      "Malformed email is rejected",
      "On the forgot-password form",
      "Enter 'bad-email'|Submit",
      "email = bad-email",
      "Snackbar 'Please enter a valid email address.'",
      "P2", "Negative", "Automated", "mobile.ForgotPasswordTest#invalidResetRequestIsRejected"),
    C("Forgot Password", "Validation", "Any", "Mobile",
      "Phone that is not 10 digits is rejected",
      "On the forgot-password form",
      "Enter a 5-digit phone|Submit",
      "phone = 55512",
      "Snackbar 'Please enter a valid 10-digit phone number.'",
      "P2", "Negative", "Automated", "mobile.ForgotPasswordTest#invalidResetRequestIsRejected"),
    C("Forgot Password", "Security", "Any", "Mobile",
      "An unknown email is indistinguishable from a registered one (no account enumeration)",
      "On the forgot-password form",
      "Enter an unregistered email|Submit|Compare the outcome with a registered email",
      "nobody+<ts>@gmail.com vs a registered address",
      "Both return the same generic 200 'OTP sent successfully.' and advance to the OTP screen; no 'not found' wording is shown and no OTP is generated for the unknown address",
      "P1", "Security", "Automated", "mobile.ForgotPasswordTest#unknownEmailIsIndistinguishableFromRegistered"),
    C("Forgot Password", "Happy path", "Any", "Mobile",
      "A registered email receives a reset code and the OTP screen opens",
      "A registered account exists",
      "Enter the registered email|Submit",
      "registered account email",
      "An OTP is stored on the user record and the 'Verification code' screen opens",
      "P1", "Functional", "Automated", "mobile.OtpTest (setup)"),
    C("Forgot Password", "Routing", "Any", "Mobile",
      "The reset role page routes Client / Professional / Admin to the same form",
      "On the reset role page",
      "Choose each role in turn",
      "-",
      "Each role opens the forgot-password form (role only scopes the lookup)",
      "P3", "Functional", "Manual", ""),

    # ---- OTP -----------------------------------------------------------------
    C("OTP", "Validation", "Any", "Mobile",
      "An incomplete OTP is rejected client-side",
      "On the 'Verification code' screen",
      "Enter 3 digits|Tap 'Verify'",
      "otp = 123",
      "Snackbar 'Please enter a valid 6-digit OTP'; no request is sent",
      "P2", "Negative", "Automated", "mobile.OtpTest#invalidOtpIsRejected"),
    C("OTP", "Backend", "Any", "Mobile",
      "A wrong 6-digit OTP is rejected by the backend",
      "On the OTP screen with a real issued code",
      "Enter 6 digits that do not match|Tap 'Verify'",
      "otp = 000000",
      "Snackbar 'Invalid OTP' (regression guard for the old Text(null) crash)",
      "P1", "Negative", "Automated", "mobile.OtpTest#invalidOtpIsRejected"),
    C("OTP", "Happy path", "Any", "Mobile",
      "The correct OTP advances to the reset-password screen",
      "An OTP was issued (readable from users.two_factor_secret)",
      "Read the issued OTP from the DB|Enter it|Tap 'Verify'",
      "-Ddb.password=… ; live OTP",
      "The Reset Password screen opens",
      "P1", "Functional", "Automated", "mobile.OtpTest#validOtpIsAccepted"),
    C("OTP", "Resend", "Any", "Mobile",
      "Resending issues a new code and invalidates the previous one",
      "On the OTP screen",
      "Tap resend|Read the new code|Submit the OLD code|Submit the NEW code",
      "-",
      "The old code is refused and the new code is accepted",
      "P2", "Functional", "Manual", ""),
    C("OTP", "Account verification", "Any", "Mobile",
      "Account verification supports both email and phone OTP resend",
      "On the account verification page after signup",
      "Tap 'Resend email OTP'|Tap 'Resend phone OTP'",
      "-",
      "Both resends succeed and their codes verify the respective channel",
      "P2", "Functional", "Manual", ""),

    # ---- Reset password ------------------------------------------------------
    C("Reset Password", "Validation", "Any", "Mobile",
      "Submitting empty fields is rejected",
      "On the Reset Password screen",
      "Leave both fields blank|Tap the 'Reset Password' button",
      "-",
      "Snackbar 'All fields are required'",
      "P2", "Negative", "Automated", "mobile.ResetPasswordTest#invalidResetIsRejected"),
    C("Reset Password", "Validation", "Any", "Mobile",
      "Mismatched passwords are rejected",
      "On the Reset Password screen",
      "Enter two different passwords|Submit",
      "Reset@2080 / Reset@9081",
      "Snackbar 'Passwords do not match'",
      "P2", "Negative", "Automated", "mobile.ResetPasswordTest#invalidResetIsRejected"),
    C("Reset Password", "Password policy", "Any", "Mobile",
      "A weak new password is rejected by the signup policy",
      "On the Reset Password screen",
      "Enter 'Trimio@1234' in both fields|Submit",
      "Trimio@1234",
      "Rejected for the sequential-digit rule — the reset screen now enforces the signup policy",
      "P2", "Negative", "Automated", "mobile.ResetPasswordTest#invalidResetIsRejected"),
    C("Reset Password", "Happy path", "Any", "Mobile",
      "A valid new password is saved and the user returns to login",
      "Reached via a correct OTP",
      "Enter a compliant password in both fields|Submit",
      "Reset@2080",
      "Success, navigation back to login, and the new password authenticates",
      "P1", "Functional", "Automated", "mobile.ResetPasswordTest#resetSucceeds"),
    C("Reset Password", "Forced reset", "Any", "Mobile",
      "A forced password reset blocks the app until a new password is set",
      "Account flagged for forced reset (e.g. a vendor temp password)",
      "Log in|Observe 'Set a new password'|Set a compliant password|Tap 'Update password & continue'",
      "temp password → new compliant password",
      "The user cannot bypass the screen; after updating they proceed to their landing screen",
      "P1", "Functional", "Manual", ""),
]
