"""Client role — booking, appointments, membership, profile, reviews, reports (mobile)."""

from . import C

SHEET = "02-Client-Mobile"
PREFIX = "CLI"

_HOME = "Logged in as a verified client on the Home tab"
_APPT = "Logged in as a client with at least one upcoming appointment"

CASES = [
    # ---- Navigation ----------------------------------------------------------
    C("Navigation", "Bottom nav", "Client", "Mobile",
      "All five client tabs open their screens",
      _HOME,
      "Tap Home|Tap Book|Tap Appointments|Tap Shop|Tap Profile",
      "-",
      "Each tab renders its screen and the selected tab is highlighted",
      "P1", "Functional", "Automated", "mobile.client.ClientNavigationTest#allTabsOpen"),
    C("Navigation", "Bottom nav", "Client", "Mobile",
      "Re-tapping the active tab pops that tab's stack back to its root",
      _HOME,
      "Open a detail screen inside a tab|Tap the same tab again",
      "-",
      "The tab returns to its root screen without losing the other tabs' state",
      "P3", "Functional", "Manual", ""),
    C("Navigation", "Bottom nav", "Client", "Mobile",
      "The Shop tab shows a live cart-count badge",
      "Logged in as a client with an empty cart",
      "Add a product to the cart|Return to any tab|Observe the Shop icon",
      "1 product",
      "The Shop tab shows a badge with the cart count; '9+' above nine items",
      "P2", "Functional", "Automated", "mobile.client.ClientStoreTest#cartBadgeReflectsCartCount"),
    C("Navigation", "Book tab", "Client", "Mobile",
      "The Book tab sends the user to Home to start a booking",
      _HOME,
      "Tap Book|Tap 'Book' on a service card",
      "-",
      "The Home tab opens with the booking flow (per the 'Open the Home tab to start a booking' hint)",
      "P2", "Functional", "Automated", "mobile.client.ClientHomeTest#bookTabHandsOffToHome"),

    # ---- Scheduled booking flow ---------------------------------------------
    C("Booking", "Flow", "Client", "Mobile",
      "The scheduled booking flow shows 4 steps with correct titles",
      _HOME,
      "Start a booking|Observe the step header and progress",
      "-",
      "Steps read 'What do you need?', 'Who & where', 'When', 'Add extras' with 'Step n of 4'",
      "P1", "Functional", "Automated", "mobile.client.ClientBookingTest#bookingFlowShowsFourSteps"),
    C("Booking", "Step 1 — What", "Client", "Mobile",
      "A service type (stylist/barber) and at least one service must be chosen to advance",
      "On booking step 1",
      "Tap Continue without selecting anything|Select a service type and a service|Tap Continue",
      "-",
      "Continue is blocked until a service is selected, then step 2 opens",
      "P1", "Functional", "Automated", "mobile.client.ClientBookingTest#step1RequiresAService"),
    C("Booking", "Step 1 — What", "Client", "Mobile",
      "Service search filters the catalogue",
      "On booking step 1",
      "Type a query into the service search box",
      "'haircut'",
      "Only matching services are listed; an empty result shows 'No services match that search.'",
      "P2", "Functional", "Automated", "mobile.client.ClientBookingTest#serviceSearchFilters"),
    C("Booking", "Step 2 — Who & where", "Client", "Mobile",
      "The saved service address is prefilled and can be edited",
      "On booking step 2 with a saved address",
      "Observe the address|Tap 'Change'|Edit the street/city|Tap 'Save address'",
      "new street + city",
      "The address updates and the hint 'Where should the pro come? This updates your saved address.' is honoured — the saved address changes",
      "P1", "Functional", "Automated", "mobile.client.ClientBookingTest#serviceAddressCanBeEdited"),
    C("Booking", "Step 2 — Who & where", "Client", "Mobile",
      "A family member can be selected as the person being served",
      "Client has at least one family member",
      "On step 2 open the person selector|Choose a family member|Continue",
      "family member",
      "The booking is attributed to that family member and carries through to review & pay",
      "P2", "Functional", "Manual", ""),
    C("Booking", "Step 3 — When", "Client", "Mobile",
      "Availability loads for the chosen day and slots are selectable",
      "On booking step 3",
      "Pick a date|Wait for 'Checking availability…' to finish|Select a slot",
      "tomorrow",
      "Open slots are listed and one can be selected; the chosen slot carries to review",
      "P1", "Functional", "Automated", "mobile.client.ClientBookingTest#availabilityLoadsForADay"),
    C("Booking", "Step 3 — When", "Client", "Mobile",
      "A fully-booked day shows the empty-availability message",
      "A date with no open slots",
      "Select that date",
      "fully-booked date",
      "'No open times on this day — try another day.' is shown and Continue stays disabled",
      "P2", "Negative", "Automated", "mobile.client.ClientBookingTest#fullyBookedDayShowsMessage"),
    C("Booking", "Step 4 — Extras", "Client", "Mobile",
      "Add-ons increase the subtotal by their listed price",
      "On booking step 4 with add-ons available",
      "Note the subtotal|Select an add-on|Observe the subtotal",
      "any add-on",
      "The subtotal rises by exactly the add-on's '+$x.xx' price",
      "P1", "Functional", "Automated", "mobile.client.ClientBookingTest#addOnUpdatesSubtotal"),
    C("Booking", "Step 4 — Extras", "Client", "Mobile",
      "No add-ons available shows the empty state",
      "Service with no add-ons",
      "Reach step 4",
      "-",
      "'No add-ons available right now.' is shown and Continue still works",
      "P3", "Functional", "Manual", ""),
    C("Booking", "Review & pay", "Client", "Mobile",
      "The review dialog itemises services, fees and the total",
      "On the review & cost dialog",
      "Inspect the breakdown",
      "-",
      "Each service line, admin override (when present), AI pricing, peak-hour and distance charges are itemised and sum to the displayed total",
      "P1", "Functional", "Manual", ""),
    C("Booking", "Review & pay", "Client", "Mobile",
      "An admin price override replaces the calculated price",
      "An active admin override matches the service/pro level",
      "Reach review & pay for that service",
      "override rule",
      "'Admin override' / 'After Admin override' rows appear and the total uses the overridden price",
      "P1", "Functional", "Manual", ""),
    C("Booking", "Review & pay", "Client", "Mobile",
      "Booking without a card on file prompts to add one",
      "Client with no saved card",
      "Reach review & pay|Tap the pay CTA",
      "-",
      "'Please add a card to cover the remaining amount.' with an 'Add a card' action; booking is not created",
      "P1", "Negative", "Manual", ""),
    C("Booking", "Review & pay", "Client", "Mobile",
      "A card can be added and saved during checkout",
      "Client with no saved card",
      "Tap 'Add a card'|Enter a Stripe test card|Tap 'Save card'",
      "4242 4242 4242 4242",
      "The card is saved and selectable; a failure surfaces 'Failed to save card: …'",
      "P1", "Functional", "Manual", ""),
    C("Booking", "Review & pay", "Client", "Mobile",
      "Membership credits are applied before charging the card",
      "Client with an active membership holding credits",
      "Book an eligible in-home service|Reach review & pay",
      "membership with ≥1 credit",
      "A 'Membership payment' row consumes a credit and the card is charged only the remainder",
      "P1", "Functional", "Manual", ""),
    C("Booking", "Review & pay", "Client", "Mobile",
      "Completing payment creates the appointment and shows confirmation",
      "Valid card on file",
      "Complete review & pay",
      "-",
      "The booking-success confirmation page is shown and the appointment appears under Appointments → Upcoming",
      "P1", "Functional", "Manual", ""),
    C("Booking", "Review & pay", "Client", "Mobile",
      "A declined card leaves no appointment behind",
      "Client with a card that will be declined",
      "Complete review & pay with a declining test card",
      "4000 0000 0000 0002",
      "A decline message is shown, no appointment row is created, and the client can retry",
      "P1", "Negative", "Manual", ""),
    C("Booking", "Conflict", "Client", "Mobile",
      "A slot taken between selection and payment surfaces 'Heads up' with 'Change time'",
      "Two clients booking the same slot",
      "Hold the slot|Have it taken|Attempt to pay",
      "-",
      "'Heads up' dialog offers 'Change time' / 'Book anyway' per the product rule, and no double-booking is created",
      "P1", "Negative", "Manual", ""),

    # ---- Group booking -------------------------------------------------------
    C("Group booking", "Flow", "Client", "Mobile",
      "The group flow shows its own step titles",
      _HOME,
      "Start a group booking|Observe the step header",
      "-",
      "Steps read \"Who's coming\", 'Services', 'Where', 'When'",
      "P2", "Functional", "Automated", "mobile.client.ClientGroupBookingTest#groupFlowShowsGroupSteps"),
    C("Group booking", "Members", "Client", "Mobile",
      "At least two people are required to continue",
      "On group step 1",
      "Continue with one person|Tap 'Add person'|Continue",
      "2 people",
      "Continue is blocked with a single participant and enabled from two",
      "P2", "Negative", "Automated", "mobile.client.ClientGroupBookingTest#groupRequiresTwoPeople"),
    C("Group booking", "Services", "Client", "Mobile",
      "Every participant needs at least one service",
      "On group step 2 with two participants",
      "Assign a service to one participant only|Attempt to continue|Assign to the second|Continue",
      "-",
      "Continue is blocked until every participant has a service",
      "P2", "Negative", "Automated", "mobile.client.ClientGroupBookingTest#everyMemberNeedsAService"),
    C("Group booking", "When", "Client", "Mobile",
      "Group availability fits the whole party into one window",
      "On group step 4",
      "Pick a date|Wait for 'Fitting the group…'",
      "-",
      "A window that accommodates all participants is proposed, or an explanatory empty state is shown",
      "P2", "Functional", "Manual", ""),

    # ---- Style Me Now (on-demand) -------------------------------------------
    C("Style Me Now", "Flow", "Client", "Mobile",
      "The on-demand flow has 2 steps",
      _HOME,
      "Start Style Me Now|Observe the header",
      "-",
      "'Who & what' then 'Where & pay', with 'Step n of 2'",
      "P1", "Functional", "Automated", "mobile.client.ClientStyleMeNowTest#flowHasTwoSteps"),
    C("Style Me Now", "Step 2", "Client", "Mobile",
      "The current GPS location is offered and a manual address can be entered",
      "On RSN step 2",
      "Observe 'Current location'|Enter a manual street address",
      "street address",
      "Either source is accepted under 'Where should we meet you?' and drives the quote",
      "P2", "Functional", "Manual", ""),
    C("Style Me Now", "Step 2", "Client", "Mobile",
      "Booking without a card shows 'No card on file — Add one to book'",
      "Client with no saved card",
      "Reach RSN step 2",
      "-",
      "The pay tile reads 'No card on file' / 'Add one to book' and the CTA is blocked",
      "P1", "Negative", "Manual", ""),
    C("Style Me Now", "Matching", "Client", "Mobile",
      "The CTA quotes the total before dispatching",
      "On RSN step 2 with a card",
      "Observe the CTA",
      "-",
      "The CTA reads 'Find a pro · $x.xx' matching the TOTAL row",
      "P1", "Functional", "Automated", "mobile.client.ClientStyleMeNowTest#ctaQuotesTheTotal"),
    C("Style Me Now", "Matching", "Client", "Mobile",
      "A matched pro shows the live ETA and map",
      "Request dispatched and accepted by a pro",
      "Wait for a match",
      "-",
      "'Your pro is on the way' with 'MIN AWAY' ETA and the shared live map",
      "P1", "Functional", "Manual", ""),
    C("Style Me Now", "Matching", "Client", "Mobile",
      "No available pro shows the 'Nobody's free right now' state with a retry",
      "No pro on duty in range",
      "Dispatch a request|Wait for expiry",
      "-",
      "\"Nobody's free right now\" with 'Try again'; no charge is captured",
      "P1", "Negative", "Manual", ""),
    C("Style Me Now", "Matching", "Client", "Mobile",
      "A request can be cancelled while matching",
      "Request in flight",
      "Tap 'Cancel request'|Confirm 'Cancel it'",
      "-",
      "'Cancel this request?' confirms; the request is cancelled and any hold released. 'Keep looking' dismisses",
      "P1", "Functional", "Manual", ""),
    C("Style Me Now", "Payment", "Client", "Mobile",
      "A declined card during dispatch is surfaced clearly",
      "Card that declines",
      "Dispatch a request",
      "4000 0000 0000 0002",
      "'Your card was declined' is shown and no pro is dispatched",
      "P1", "Negative", "Manual", ""),

    # ---- Recurrence ----------------------------------------------------------
    C("Recurring", "Setup", "Client", "Mobile",
      "A recurring appointment can be created with pattern, interval and count",
      "In the booking flow with recurrence available",
      "Open 'Recurring Appointment'|Set a pattern, interval and count|Confirm",
      "weekly / 1 / 4",
      "The series is created; the appointment detail shows Pattern, Interval and Count",
      "P2", "Functional", "Manual", ""),
    C("Recurring", "Cancellation", "Client", "Mobile",
      "Cancelling a recurring appointment offers 'Only this visit' vs 'All future visits'",
      "Client with an active series",
      "Open a series appointment|Tap 'Cancel appointment'",
      "-",
      "'Cancel next upcoming visit only?' with both options; each cancels exactly its scope",
      "P1", "Functional", "Manual", ""),

    # ---- Appointments --------------------------------------------------------
    C("Appointments", "List", "Client", "Mobile",
      "Upcoming / past appointment tabs list the right rows",
      _APPT,
      "Open Appointments|Switch between the tabs",
      "-",
      "Each tab lists only its appointments; empty tabs show 'No <tab> appointments.'",
      "P1", "Functional", "Automated", "mobile.client.ClientAppointmentsTest#tabsListAppointments"),
    C("Appointments", "Detail", "Client", "Mobile",
      "Appointment detail shows services, professional, price and payment",
      _APPT,
      "Open an appointment",
      "-",
      "'Appointment #<id>' with per-service prices, the professional, the total and the payment record",
      "P1", "Functional", "Automated", "mobile.client.ClientAppointmentsTest#detailShowsSummary"),
    C("Appointments", "Detail", "Client", "Mobile",
      "Missing sub-records show their empty states rather than blank space",
      "An appointment with no mileage/payment/services data",
      "Open the appointment detail",
      "-",
      "'No mileage data available.', 'No payment recorded.', 'No services added.' as appropriate",
      "P3", "Functional", "Manual", ""),
    C("Appointments", "Update", "Client", "Mobile",
      "Date/time can be updated on an upcoming appointment",
      _APPT,
      "Open an upcoming appointment|Tap 'Update date / time'|Pick a new slot|Confirm",
      "new slot",
      "The appointment moves to the new slot and both parties are notified",
      "P1", "Functional", "Manual", ""),
    C("Appointments", "Cancel", "Client", "Mobile",
      "A single appointment can be cancelled and 'Keep appointment' aborts",
      _APPT,
      "Open an appointment|Tap 'Cancel appointment'|Tap 'Keep appointment'|Repeat and confirm the cancel",
      "-",
      "'Keep appointment' leaves it untouched; confirming moves it to cancelled and applies the cancellation policy",
      "P1", "Functional", "Manual", ""),
    C("Appointments", "Rebook", "Client", "Mobile",
      "'Rebook' pre-fills the flow with the previous professional and services",
      "Client with a completed appointment",
      "Open a past appointment|Tap 'Rebook'",
      "-",
      "The booking flow opens pre-filled ('Book your professional?'); a failure shows 'Could not start rebooking. Please try again.'",
      "P2", "Functional", "Manual", ""),
    C("Appointments", "Countdown", "Client", "Mobile",
      "An in-progress appointment shows the live countdown/marquee",
      "Appointment currently in progress",
      "Open the Appointments tab",
      "-",
      "The countdown/marquee banner for the in-progress visit is displayed",
      "P3", "Functional", "Manual", ""),
    C("Appointments", "Post-service", "Client", "Mobile",
      "The post-service prompt offers rating and tipping",
      "An appointment has just completed",
      "Open the app|Observe the prompt",
      "-",
      "'How was it with <pro>?' with 'Rate your visit', 'ADD A TIP' and 'Not now'",
      "P2", "Functional", "Manual", ""),
    C("Appointments", "Tipping", "Client", "Mobile",
      "A preset tip is charged in full to the professional",
      "Card on file; completed appointment",
      "Open the tip card|Choose a preset amount|Confirm",
      "$5",
      "'Thanks — $5 sent to <pro>' and the note '100% goes to your pro — Trimio takes nothing.' holds — the pro receives the full amount",
      "P1", "Functional", "Manual", ""),
    C("Appointments", "Tipping", "Client", "Mobile",
      "A custom tip amount is accepted and validated",
      "Card on file; completed appointment",
      "Choose 'Custom'|Enter an amount|Confirm|Repeat with 0 / a non-numeric value",
      "12.50 then 0",
      "A valid custom amount is charged; invalid input shows 'Enter a valid amount.'",
      "P2", "Negative", "Manual", ""),
    C("Appointments", "Tipping", "Client", "Mobile",
      "Tipping without a card prompts to add one",
      "Client with no card",
      "Open the tip card",
      "-",
      "'Add a card on file to leave a tip.'",
      "P2", "Negative", "Manual", ""),

    # ---- Reviews -------------------------------------------------------------
    C("Reviews", "Flow", "Client", "Mobile",
      "The review flow requires a star rating before continuing",
      "Completed appointment awaiting review",
      "Open 'Leave a Review'|Continue without rating",
      "-",
      "'Please choose a star rating' / 'Please answer before continuing'",
      "P2", "Negative", "Automated", "mobile.client.ClientReviewTest#ratingIsRequired"),
    C("Reviews", "Flow", "Client", "Mobile",
      "Every service received must be rated",
      "Appointment with two services",
      "Rate one service|Attempt to continue",
      "-",
      "'Please rate all your services before continuing.'",
      "P2", "Negative", "Automated", "mobile.client.ClientReviewTest#allServicesMustBeRated"),
    C("Reviews", "Flow", "Client", "Mobile",
      "All required aspect sliders must be set",
      "In the review flow",
      "Leave a required slider untouched|Continue",
      "-",
      "'Please rate all required sliders before continuing.'",
      "P2", "Negative", "Manual", ""),
    C("Reviews", "Flow", "Client", "Mobile",
      "The public review requires at least 20 characters",
      "In the review flow",
      "Enter a 10-character comment|Submit",
      "'great job'",
      "'Please write at least 20 characters for your review.'",
      "P2", "Negative", "Automated", "mobile.client.ClientReviewTest#publicReviewMinimumLength"),
    C("Reviews", "Flow", "Client", "Mobile",
      "A complete review submits successfully",
      "In the review flow",
      "Rate everything|Write a 20+ character review|Answer 'Would you book again?'|Submit",
      "5 stars, 40-char comment",
      "'✅ Thanks for your review!' and the review appears on the professional's profile",
      "P1", "Functional", "Manual", ""),
    C("Reviews", "Photos", "Client", "Mobile",
      "Photos can be attached to a review",
      "In the review flow",
      "Tap 'Add Photos (Optional)'|Attach an image|Submit",
      "1 image",
      "The photo uploads and is visible in the review's photo viewer",
      "P2", "Functional", "Manual", ""),
    C("Reviews", "Private feedback", "Client", "Mobile",
      "Private feedback is stored but not shown publicly",
      "In the review flow",
      "Fill 'Private Feedback (only visible to Trimio)'|Submit|View the public review",
      "private text",
      "The private text is not rendered on the public review; admins can see it",
      "P1", "Security", "Manual", ""),
    C("Reviews", "Escalation", "Client", "Mobile",
      "'Report an issue to support' from the review flow opens a report",
      "In the review flow",
      "Tap 'Report an issue to support'",
      "-",
      "The create-report screen opens pre-linked to the appointment",
      "P2", "Functional", "Manual", ""),
    C("Reviews", "Browse", "Client", "Mobile",
      "Reviews list supports sorting and rating filters",
      "A professional with several reviews",
      "Open reviews|Sort by 'Most recent' / 'Highest rated' / 'Lowest rated'|Filter '5★ only' and 'With comments'",
      "-",
      "The list re-orders/filters correctly; the rating distribution matches the shown reviews",
      "P2", "Functional", "Manual", ""),
    C("Reviews", "Browse", "Client", "Mobile",
      "A professional with fewer than 3 reviews shows the minimum-reviews notice",
      "Professional with 2 reviews",
      "Open the professional's rating",
      "-",
      "'Minimum 3 reviews required to calculate rating.' instead of an average",
      "P3", "Functional", "Manual", ""),

    # ---- Membership ----------------------------------------------------------
    C("Membership", "Plans", "Client", "Mobile",
      "Available plans are listed with price and allotment",
      "Logged in as a client without a membership",
      "Open Membership → 'Choose your plan'",
      "-",
      "Each plan shows its name, $x/mo and '<n> in-home cuts/month'; no plans shows 'No plans available right now.'",
      "P1", "Functional", "Automated", "mobile.client.ClientMembershipTest#plansAreListed"),
    C("Membership", "Checkout", "Client", "Mobile",
      "Membership checkout validates billing details",
      "On the membership checkout page",
      "Submit with an empty cardholder name / receipt email",
      "-",
      "Validation blocks submission until 'Cardholder name' and 'Email for receipt' are provided",
      "P2", "Negative", "Manual", ""),
    C("Membership", "Checkout", "Client", "Mobile",
      "Subscribing activates the membership",
      "Valid card details",
      "Tap 'Subscribe — $x/mo'|Complete the Stripe payment",
      "4242 4242 4242 4242",
      "'Membership activated successfully' / 'Welcome to <plan>!', credits are granted and the plan shows as Active",
      "P1", "Functional", "Manual", ""),
    C("Membership", "Manage", "Client", "Mobile",
      "Manage plan shows the remaining credits and renewal date",
      "Client with an active membership",
      "Open 'Manage plan'",
      "-",
      "'<a> of <b> credits left' and '$x.xx/mo · renews <date>' with status Active",
      "P1", "Functional", "Automated", "mobile.client.ClientMembershipTest#managePlanShowsCredits"),
    C("Membership", "Upgrade", "Client", "Mobile",
      "A plan can be upgraded and the allotment changes",
      "Client on the lowest plan",
      "Open 'Upgrade your plan'|Choose a higher plan|Confirm",
      "higher plan",
      "The subscription upgrades, the new allotment applies and billing is prorated",
      "P1", "Functional", "Manual", ""),
    C("Membership", "Pause", "Client", "Mobile",
      "A membership can be paused for up to 2 months",
      "Client with an active membership",
      "Open Manage plan|Tap 'Pause'|Confirm 'Pause membership?'",
      "-",
      "Billing pauses for the selected period; 'Not now' aborts without changes",
      "P2", "Functional", "Manual", ""),
    C("Membership", "Cancel", "Client", "Mobile",
      "Cancellation shows the refund calculation and retention options",
      "Client with an active membership",
      "Tap 'Cancel membership'|Observe 'Calculating your refund…'|Review 'Not ready to leave? Other options'",
      "-",
      "A refund amount is computed, 'Pause for up to 2 months instead' is offered, and 'Keep my membership' aborts",
      "P1", "Functional", "Manual", ""),
    C("Membership", "Cancel", "Client", "Mobile",
      "Confirming cancellation ends the membership and stops future billing",
      "In the cancel flow",
      "Select a reason|Confirm 'Cancel membership?'",
      "reason from the dropdown",
      "The membership ends per the policy, no further invoices are issued and credits behave per the expiry rules",
      "P1", "Functional", "Manual", ""),
    C("Membership", "Billing history", "Client", "Mobile",
      "Invoices are listed and a PDF can be opened",
      "Client with at least one invoice",
      "Open 'Billing history'|Tap 'PDF' on an invoice",
      "-",
      "Invoices show amount and date; the PDF opens. No invoices shows 'No invoices yet'",
      "P2", "Functional", "Manual", ""),
    C("Membership", "Credits", "Client", "Mobile",
      "Expired credits are not spendable",
      "Client whose credits have passed their expiry",
      "Attempt to book using a credit",
      "-",
      "The expired credit is not applied and the card is charged the full amount",
      "P2", "Negative", "Manual", ""),

    # ---- Profile -------------------------------------------------------------
    C("Profile", "Account", "Client", "Mobile",
      "Profile shows the current plan and 'Edit your details' works",
      "Logged in as a client",
      "Open Profile|Tap 'Edit your details'|Change a field|Save",
      "new display name",
      "'Current plan:' reflects the membership; edits persist after reopening the screen",
      "P2", "Functional", "Automated", "mobile.client.ClientProfileTest#profileShowsAccountDetails"),
    C("Profile", "Account", "Client", "Mobile",
      "Leaving the profile editor with unsaved changes prompts to discard",
      "Editing the profile",
      "Change a field|Navigate back",
      "-",
      "'Discard changes?' with 'Keep editing' / 'Discard' / 'Save anyway'",
      "P3", "Functional", "Manual", ""),
    C("Profile", "Biometrics", "Client", "Mobile",
      "Fingerprint login can be toggled on and off",
      "Device with biometrics enrolled",
      "Open Profile|Toggle fingerprint login on|Toggle it off",
      "-",
      "'Fingerprint login enabled' / 'Fingerprint login disabled'; devices without biometrics show 'Biometric authentication is not available on this device'",
      "P3", "Functional", "Manual", ""),
    C("Profile", "Family", "Client", "Mobile",
      "A family member can be added and removed",
      "Logged in as a client",
      "Open family members|Tap 'Add someone'|Fill the details and save|Remove them and confirm",
      "family member name/age",
      "The member is listed and bookable; 'Remove this person?' confirms deletion",
      "P2", "Functional", "Manual", ""),
    C("Profile", "Addresses", "Client", "Mobile",
      "Postal code and phone inputs are format-enforced",
      "Editing the client profile",
      "Enter a malformed postal code and phone",
      "'abc' / '123'",
      "The formatters reject/normalise the input and the form cannot be saved with an invalid value",
      "P3", "Negative", "Manual", ""),

    # ---- Reports / support ---------------------------------------------------
    C("Reports", "Create", "Client", "Mobile",
      "A support report can be filed against an appointment",
      "Client with a completed appointment",
      "Open Reports|Create a report|Choose a category and describe the issue|Submit",
      "category + description",
      "The report is created and appears in the client's report list and the admin Reports queue",
      "P1", "Functional", "Manual", ""),
    C("Reports", "List", "Client", "Mobile",
      "Filed reports and their statuses are visible to the client",
      "Client with at least one report",
      "Open the reports list|Open a report",
      "-",
      "Each report shows its status and admin responses",
      "P2", "Functional", "Manual", ""),

    # ---- Discovery / misc ----------------------------------------------------
    C("Discovery", "Search", "Client", "Mobile",
      "Home search finds services, professionals and styles",
      _HOME,
      "Type into 'Search services, pros, or styles'",
      "'fade'",
      "Matching services/pros/styles are returned; an empty query restores the default feed",
      "P2", "Functional", "Automated", "mobile.client.ClientHomeTest#searchReturnsResults"),
    C("Discovery", "Activity", "Client", "Mobile",
      "The Book tab lists service categories and 'Browse all services'",
      _HOME,
      "Open the Book tab",
      "-",
      "'A licensed pro comes to you — pick a service to get started.' with categories and 'Browse all services'",
      "P2", "Functional", "Automated", "mobile.client.ClientHomeTest#bookTabListsServices"),
    C("Discovery", "Scan to book", "Client", "Mobile",
      "Scanning a professional's QR code opens their booking",
      "A valid pro referral QR code",
      "Open 'Scan to book'|Scan the code",
      "pro QR",
      "The referral is resolved and the booking flow opens for that professional; flash/camera toggles work",
      "P2", "Functional", "Manual", ""),
    C("Discovery", "Portfolio", "Client", "Mobile",
      "A professional's portfolio gallery opens from their profile",
      "Professional with portfolio images",
      "Open the pro's profile|Open '<name> – Portfolio'",
      "-",
      "Portfolio images render and can be browsed full-screen",
      "P3", "Functional", "Manual", ""),
    C("Notifications", "List", "Client", "Mobile",
      "Notifications list and 'Mark all read' clears the unread badge",
      "Client with unread notifications",
      "Open Notifications|Tap 'Mark all read'",
      "-",
      "All items become read and the badge clears",
      "P2", "Functional", "Manual", ""),
    C("Map", "Navigation", "Client", "Mobile",
      "The client can follow the professional's live location en route",
      "Appointment with a pro en route",
      "Open the appointment's map",
      "-",
      "The pro's position and ETA update live",
      "P2", "Functional", "Manual", ""),
]
