"""Cross-cutting concerns — security, permissions, performance, compatibility, data integrity."""

from . import C

SHEET = "07-Cross-Cutting"
PREFIX = "XCT"

CASES = [
    # ---- Authorisation -------------------------------------------------------
    C("Security", "Authorisation", "Any", "API",
      "Admin endpoints refuse a client or professional token",
      "Valid client and professional sessions",
      "Call /admin/*, /store/admin/* and /v1/admin/enforcements/* with each token",
      "-",
      "Every call is refused (401/403) and returns no admin data",
      "P1", "Security", "Manual", ""),
    C("Security", "Authorisation", "Any", "API",
      "Vendor endpoints are scoped to the calling vendor",
      "Two vendors with products and orders",
      "Call /store/vendor/products and /store/vendor/orders as vendor A, referencing vendor B's ids",
      "vendor B product/order ids",
      "Only vendor A's own records are returned or mutable — cross-vendor ids are refused",
      "P1", "Security", "Manual", ""),
    C("Security", "Authorisation", "Client", "API",
      "A client cannot read another client's orders or appointments",
      "Two client accounts with data",
      "Request client B's order and appointment ids using client A's session",
      "-",
      "Refused — no cross-tenant data leaks (IDOR check)",
      "P1", "Security", "Manual", ""),
    C("Security", "Authentication", "Any", "API",
      "Protected endpoints refuse missing or expired tokens",
      "-",
      "Call a protected endpoint with no token, a malformed token and an expired token",
      "-",
      "Each is rejected with 401 and no data",
      "P1", "Security", "Manual", ""),
    C("Security", "Input", "Any", "Both",
      "Free-text fields reject or neutralise script payloads",
      "-",
      "Submit an XSS payload in a review, note, report and product description|View it back",
      "<script>alert(1)</script>",
      "The payload is stored escaped and rendered as text — never executed, in the app or the portal",
      "P1", "Security", "Manual", ""),
    C("Security", "Input", "Any", "API",
      "Search and filter parameters are not SQL-injectable",
      "-",
      "Send SQL metacharacters in search/filter parameters",
      "' OR 1=1 --",
      "Parameters are bound; no error leak and no unauthorised rows returned",
      "P1", "Security", "Manual", ""),
    C("Security", "Secrets", "Any", "Both",
      "No secrets or PII leak into logs or client bundles",
      "-",
      "Inspect app logs, the browser console and the web bundle",
      "-",
      "No API keys, passwords, tokens or full card data are present",
      "P1", "Security", "Manual", ""),
    C("Security", "Payments", "Any", "Both",
      "Card data never reaches Trimio servers",
      "-",
      "Complete a booking, membership and store checkout while capturing traffic",
      "Stripe test cards",
      "PANs go only to Stripe; Trimio stores tokens/ids only",
      "P1", "Security", "Manual", ""),
    C("Security", "Rate limiting", "Any", "API",
      "Repeated failed logins are throttled or locked out",
      "A registered account",
      "Attempt 10 consecutive wrong-password logins",
      "-",
      "Throttling/lockout is applied rather than unlimited attempts",
      "P2", "Security", "Manual", ""),
    C("Security", "Password storage", "Any", "API",
      "Stored password material is not reversible plaintext",
      "DB access",
      "Inspect users.password_hash for a known account",
      "-",
      "Only a hash is stored (note: the current implementation is raw SHA-256 of the plaintext — flagged as a hardening item, no per-user salt or KDF)",
      "P1", "Security", "Manual", ""),

    # ---- Permissions & device ------------------------------------------------
    C("Permissions", "Location", "Client", "Mobile",
      "Denying location degrades gracefully",
      "Fresh install",
      "Deny the location permission|Attempt a Style-Me-Now booking",
      "-",
      "The app explains the requirement and offers manual address entry instead of crashing",
      "P2", "Reliability", "Manual", ""),
    C("Permissions", "Camera", "Client", "Mobile",
      "Denying camera blocks scan-to-book with an explanation",
      "Fresh install",
      "Deny the camera permission|Open 'Scan to book'",
      "-",
      "A clear explanation is shown; no crash",
      "P3", "Reliability", "Manual", ""),
    C("Permissions", "Notifications", "Any", "Mobile",
      "Denying push notifications does not break the app",
      "Fresh install",
      "Deny notifications|Complete a booking",
      "-",
      "In-app flows work; only push delivery is absent",
      "P3", "Reliability", "Manual", ""),

    # ---- Connectivity & reliability -----------------------------------------
    C("Reliability", "Offline", "Any", "Mobile",
      "Losing connectivity mid-flow shows an error and does not double-submit",
      "In a booking or checkout flow",
      "Disable the network|Submit|Re-enable and retry",
      "-",
      "A network error is shown, no partial record is created, and the retry succeeds exactly once",
      "P1", "Reliability", "Manual", ""),
    C("Reliability", "Backend down", "Any", "Both",
      "A backend outage surfaces retryable errors, not blank screens",
      "Backend stopped",
      "Open the dashboards/lists that fetch data",
      "-",
      "'Retry' affordances are shown (the pattern used across the app) rather than empty or frozen screens",
      "P2", "Reliability", "Manual", ""),
    C("Reliability", "Idempotency", "Client", "Both",
      "Double-tapping pay does not charge twice",
      "At a payment step",
      "Tap the pay CTA twice rapidly",
      "-",
      "Exactly one charge and one order/appointment are created",
      "P1", "Reliability", "Manual", ""),
    C("Reliability", "Background", "Any", "Mobile",
      "Backgrounding and restoring the app preserves in-progress flow state",
      "Mid-way through the booking flow",
      "Background the app for 2 minutes|Restore it",
      "-",
      "The step and selections are preserved or the user is returned to a safe, consistent point",
      "P2", "Reliability", "Manual", ""),

    # ---- Performance ---------------------------------------------------------
    C("Performance", "Startup", "Any", "Mobile",
      "Cold start reaches the first interactive screen within budget",
      "Release build on a mid-range device",
      "Cold start the app 5 times and measure",
      "-",
      "Median time to interactive is within the agreed budget (e.g. ≤ 3s)",
      "P2", "Performance", "Manual", ""),
    C("Performance", "Lists", "Any", "Both",
      "Large lists scroll smoothly and paginate",
      "1000+ users / products / orders",
      "Scroll the admin user list, the shop and the vendor orders",
      "-",
      "No dropped frames or unbounded memory growth; pagination loads incrementally",
      "P2", "Performance", "Manual", ""),
    C("Performance", "API", "Any", "API",
      "Key endpoints respond within budget under nominal load",
      "Seeded environment",
      "Measure /auth/login, availability, /store/client/products and admin counts",
      "-",
      "p95 latency within the agreed budget",
      "P2", "Performance", "Manual", ""),
    C("Performance", "Web", "Admin", "Web",
      "The portal's first meaningful paint is acceptable on a cold cache",
      "Deployed portal",
      "Load the portal with the cache disabled",
      "-",
      "The shell renders within the agreed budget; the Flutter bundle size is tracked",
      "P3", "Performance", "Manual", ""),

    # ---- Compatibility -------------------------------------------------------
    C("Compatibility", "Android", "Any", "Mobile",
      "The app works across the supported Android versions",
      "Devices/emulators on min and latest supported API levels",
      "Run the smoke journey on each",
      "-",
      "No layout breakage or API-level crashes",
      "P2", "Compatibility", "Manual", ""),
    C("Compatibility", "Screen sizes", "Any", "Mobile",
      "Layouts hold on small and large screens",
      "Small phone and tablet",
      "Run the smoke journey on each",
      "-",
      "No clipped controls; the taller forms remain reachable with the keyboard open",
      "P2", "Compatibility", "Manual", ""),
    C("Compatibility", "Locale", "Any", "Both",
      "Currency and dates render correctly under a non-US locale",
      "Device set to a non-US locale",
      "View prices, invoices and appointment dates",
      "-",
      "Amounts and dates are formatted consistently and are not corrupted",
      "P3", "Compatibility", "Manual", ""),
    C("Compatibility", "Dark mode", "Any", "Both",
      "The UI is legible in dark mode",
      "Device/browser set to dark",
      "Walk the main screens",
      "-",
      "No unreadable text or invisible controls",
      "P3", "Compatibility", "Manual", ""),

    # ---- Accessibility -------------------------------------------------------
    C("Accessibility", "Screen reader", "Any", "Mobile",
      "Key controls are announced meaningfully",
      "TalkBack enabled",
      "Traverse login, booking and checkout",
      "-",
      "Buttons and fields announce their purpose (this is also what makes them automatable)",
      "P2", "Accessibility", "Manual", ""),
    C("Accessibility", "Contrast", "Any", "Both",
      "Text meets contrast requirements",
      "-",
      "Audit the primary screens",
      "-",
      "Contrast ratios meet WCAG AA",
      "P3", "Accessibility", "Manual", ""),

    # ---- Data integrity ------------------------------------------------------
    C("Data", "Money", "Any", "API",
      "Monetary amounts round-trip without floating-point drift",
      "Orders and appointments with awkward amounts",
      "Compare stored cents against displayed dollars across app, portal and DB",
      "$19.99, $0.01, $1234.56",
      "Every surface agrees to the cent",
      "P1", "Data Integrity", "Manual", ""),
    C("Data", "Timezones", "Any", "Both",
      "Appointment times are consistent across client, professional and admin",
      "Client and professional in different timezones",
      "Book an appointment and compare all three views",
      "-",
      "All parties see the same instant, correctly localised",
      "P1", "Data Integrity", "Manual", ""),
    C("Data", "Deletion", "Any", "API",
      "Deleting a record leaves no orphaned dependents",
      "A vendor with products, orders and payouts",
      "Delete/suspend the vendor",
      "-",
      "Dependent records are handled per the policy — no dangling references or crashes",
      "P2", "Data Integrity", "Manual", ""),
    C("Data", "Concurrency", "Any", "API",
      "Concurrent updates to the same record do not corrupt it",
      "Two admins editing the same override/vendor",
      "Save conflicting changes simultaneously",
      "-",
      "One write wins cleanly; no partial or interleaved state",
      "P2", "Data Integrity", "Manual", ""),

    # ---- Test-infrastructure health -----------------------------------------
    C("Test Infra", "Mobile", "Any", "Mobile",
      "The mobile suite runs green against a booted emulator with the backend up",
      "Emulator booted, backend on :3000, Postgres up",
      "mvn test -DsuiteXmlFile=src/test/resources/suites/mobile-testng.xml -Ddb.password=…",
      "-",
      "All non-skipped tests pass and the Extent report is produced",
      "P1", "Test Infra", "Automated", "mobile-testng.xml"),
    C("Test Infra", "Web", "Any", "Web",
      "The web suite runs green against the served portal",
      "Portal served at web.baseUrl; backend up",
      "mvn test -DsuiteXmlFile=src/test/resources/suites/web-testng.xml -Dweb.baseUrl=…",
      "-",
      "All non-skipped tests pass",
      "P1", "Test Infra", "Automated", "web-testng.xml"),
    C("Test Infra", "Reporting", "Any", "Both",
      "Failures capture a screenshot and appear in the Extent report",
      "-",
      "Force a failure and inspect reports/",
      "-",
      "The report contains the failure with its screenshot and log context",
      "P2", "Test Infra", "Automated", "listeners.TestListener"),
    C("Test Infra", "Retry", "Any", "Both",
      "Flaky-test retry is configurable and off by default in verification runs",
      "-",
      "Run with -DretryCount=0 and with the default",
      "-",
      "The retry count is honoured (retryCount=0 avoids masking real failures)",
      "P3", "Test Infra", "Automated", "listeners.RetryAnalyzer"),
]
