"""Professional role — onboarding, offers, bookings, clients, earnings, profile (mobile)."""

from . import C

SHEET = "03-Professional-Mobile"
PREFIX = "PRO"

_PRO = "Logged in as an approved professional on the Dashboard tab"

CASES = [
    # ---- Onboarding / approval gate -----------------------------------------
    C("Onboarding", "Approval gate", "Professional", "Mobile",
      "A professional without a profile is routed to the profile-creation screen",
      "Professional account with an empty profile",
      "Log in as that professional",
      "-",
      "ProfessionalNotCreatedHomePage is shown; the dashboard tabs are not reachable until the profile exists",
      "P1", "Functional", "Manual", ""),
    C("Onboarding", "Approval gate", "Professional", "Mobile",
      "A professional with approval_status='pending' cannot take bookings",
      "Professional whose profile is pending admin approval",
      "Log in|Attempt to reach the dashboard/offers",
      "-",
      "The pending state is enforced — no offers are received and the profile screen explains the pending review",
      "P1", "Functional", "Manual", ""),
    C("Onboarding", "Personal data", "Professional", "Mobile",
      "The personal-data form requires every mandatory field",
      "On the professional personal-data form",
      "Submit with fields missing",
      "-",
      "'Please select all required fields.' and nothing is saved",
      "P2", "Negative", "Manual", ""),
    C("Onboarding", "Sensitive data", "Professional", "Mobile",
      "The licence number is format-enforced (FXXX-XXX-XX-XXX-X)",
      "On the sensitive-data form",
      "Enter a licence number in the wrong format|Enter one in the right format",
      "F123-456-78-901-2",
      "The formatter enforces the mask; only a well-formed licence saves",
      "P2", "Negative", "Manual", ""),
    C("Onboarding", "Sensitive data", "Professional", "Mobile",
      "All required identity images must be uploaded",
      "On the sensitive-data form",
      "Save without uploading all images|Upload via 'Take a photo' and 'Choose from gallery'|Save",
      "ID front/back images",
      "'Please upload all required images.' until every image is attached, then the form saves",
      "P1", "Negative", "Manual", ""),
    C("Onboarding", "Session guard", "Professional", "Mobile",
      "A missing session on the profile forms is reported, not swallowed",
      "Prefs cleared while the form is open",
      "Attempt to save",
      "-",
      "'User ID is missing. Please log in again.'",
      "P3", "Negative", "Manual", ""),

    # ---- Licensing -----------------------------------------------------------
    C("Licensing", "State licence", "Professional", "Mobile",
      "A state-board licence can be added and submitted for review",
      "Logged in as a professional with no licence",
      "Open 'State board licenses'|Tap 'Add a license'|Fill the details and attach the document|Tap 'Submit for review'",
      "state + licence no. + document",
      "'Submitted for Trimio to verify before you can be booked.' and the licence appears in the admin verification queue",
      "P1", "Functional", "Manual", ""),
    C("Licensing", "State licence", "Professional", "Mobile",
      "No licence shows the empty state and blocks bookability",
      "Professional with no licence",
      "Open the licence page",
      "-",
      "'No state license added yet' and the professional cannot be booked",
      "P1", "Functional", "Manual", ""),
    C("Licensing", "Rejection", "Professional", "Mobile",
      "A rejected licence shows the admin's reason",
      "Admin rejected the licence with a note",
      "Open the licence page",
      "-",
      "The rejected status and 'Reason: <notes>' are shown, with the option to resubmit",
      "P2", "Functional", "Manual", ""),
    C("Licensing", "Removal", "Professional", "Mobile",
      "A licence can be removed",
      "Professional with a licence on file",
      "Tap 'Remove' on the licence|Confirm",
      "-",
      "The licence is removed and the bookability gate reapplies",
      "P3", "Functional", "Manual", ""),

    # ---- Dashboard & offers --------------------------------------------------
    C("Dashboard", "Landing", "Professional", "Mobile",
      "The dashboard renders the five professional tabs",
      _PRO,
      "Log in as a professional|Observe the bottom nav",
      "-",
      "DashBoard / My Bookings / Client Hub / Store / Account are present and each opens",
      "P1", "Functional", "Automated", "mobile.professional.ProfessionalDashboardTest#dashboardTabsOpen"),
    C("Dashboard", "On duty", "Professional", "Mobile",
      "The on-duty toggle controls offer eligibility",
      _PRO,
      "Toggle on duty off|Have a client dispatch a nearby request|Toggle on duty on",
      "-",
      "No offers arrive while off duty; offers resume when on duty",
      "P1", "Functional", "Manual", ""),
    C("Dashboard", "Offers", "Professional", "Mobile",
      "An incoming offer shows the payout breakdown",
      "On duty with an incoming offer",
      "Observe the offer card",
      "-",
      "'you earn $x.xx' with the note 'Service pay + mileage · convenience fee goes to Trimio', plus any '+$x bonus'",
      "P1", "Functional", "Automated", "mobile.professional.ProfessionalDashboardTest#offerShowsPayoutBreakdown"),
    C("Dashboard", "Offers", "Professional", "Mobile",
      "Accepting an offer creates the appointment for both parties",
      "Incoming offer",
      "Accept the offer",
      "-",
      "The appointment appears under My Bookings and the client sees 'Matched with <pro>'",
      "P1", "Functional", "Manual", ""),
    C("Dashboard", "Offers", "Professional", "Mobile",
      "Declining an offer releases it to other professionals",
      "Incoming offer",
      "Tap 'Decline'",
      "-",
      "The offer leaves this professional's queue and is re-offered per the scoring rules",
      "P1", "Functional", "Manual", ""),
    C("Dashboard", "Offers", "Professional", "Mobile",
      "Offers can be sorted 'Nearest first'",
      "Several open offers",
      "Apply the 'Nearest first' sort",
      "-",
      "Offers are ordered by ascending distance",
      "P3", "Functional", "Manual", ""),
    C("Dashboard", "In progress", "Professional", "Mobile",
      "An in-progress appointment is surfaced on the dashboard",
      "Professional with a started appointment",
      "Open the dashboard",
      "-",
      "'You have an appointment in progress...' banner links to the appointment",
      "P2", "Functional", "Manual", ""),
    C("Dashboard", "Earnings", "Professional", "Mobile",
      "The 'Earned' figure matches completed-appointment payouts",
      "Professional with completed appointments",
      "Compare the dashboard 'Earned' value with the balance/transactions",
      "-",
      "The figures reconcile",
      "P1", "Functional", "Manual", ""),

    # ---- Bookings ------------------------------------------------------------
    C("Bookings", "List", "Professional", "Mobile",
      "The bookings dashboard lists appointments with price",
      "Professional with appointments",
      "Open My Bookings",
      "-",
      "Each row shows the client, service and '$<price>'; 'View details' opens the appointment",
      "P1", "Functional", "Automated", "mobile.professional.ProfessionalBookingsTest#bookingsAreListed"),
    C("Bookings", "Search", "Professional", "Mobile",
      "Bookings can be searched by client or service",
      "Professional with several appointments",
      "Type into 'Search clients or services'",
      "client name",
      "Only matching appointments remain listed",
      "P2", "Functional", "Automated", "mobile.professional.ProfessionalBookingsTest#searchFiltersBookings"),
    C("Bookings", "Cancel", "Professional", "Mobile",
      "A professional can cancel an appointment, with 'Keep' aborting",
      "Professional with an upcoming appointment",
      "Open the appointment|Tap 'Cancel appointment'|Tap 'Keep'|Repeat and confirm",
      "-",
      "'Keep' aborts; confirming cancels, notifies the client and applies the pro-cancellation policy",
      "P1", "Functional", "Manual", ""),
    C("Bookings", "No-show", "Professional", "Mobile",
      "Reporting a client no-show charges the §5.5 fee",
      "Appointment past its start time",
      "Open the appointment|Tap 'Report no-show'|Confirm",
      "-",
      "The no-show is recorded and the fee described by 'Charges the §5.5 no-show fee' is applied",
      "P1", "Functional", "Manual", ""),
    C("Bookings", "Recurring", "Professional", "Mobile",
      "Cancelling a recurring visit offers 'Only this visit' / 'All future visits'",
      "Professional with a recurring series",
      "Open a series appointment|Cancel",
      "-",
      "Both scopes are offered and each cancels exactly its scope",
      "P1", "Functional", "Manual", ""),
    C("Bookings", "Sanitation", "Professional", "Mobile",
      "The sanitation attestation must be completed and is stored",
      "Professional on an appointment detail",
      "Open the 'Sanitation checklist'|Tick each item|Tap 'Save attestation'",
      "kit disinfected / single-use items / water access",
      "All three attestations are saved against the appointment",
      "P2", "Functional", "Manual", ""),
    C("Bookings", "Navigation", "Professional", "Mobile",
      "Turn-by-turn navigation and 'Message Client' open from the appointment",
      "Accepted appointment with an address",
      "Open the navigation map|Tap 'Message Client'",
      "-",
      "The map routes to the client's address and messaging opens the chat",
      "P2", "Functional", "Manual", ""),

    # ---- Schedule ------------------------------------------------------------
    C("Schedule", "Availability", "Professional", "Mobile",
      "Working hours can be updated and drive client availability",
      "Logged in as a professional",
      "Open Schedule|Change the working window for a day|Save|Check that day as a client",
      "09:00–17:00",
      "The schedule saves and the client booking flow offers only slots inside it; a failure shows 'Error updating schedule'",
      "P1", "Functional", "Manual", ""),
    C("Schedule", "Calendar", "Professional", "Mobile",
      "Google Calendar can be linked and appointments sync",
      "Professional with a Google account",
      "Open 'Google Calendar'|Authorise|Create an appointment",
      "-",
      "The appointment appears on the linked calendar",
      "P3", "Functional", "Manual", ""),

    # ---- Client hub ----------------------------------------------------------
    C("Client Hub", "List", "Professional", "Mobile",
      "The client list shows visit count and total spend",
      "Professional with repeat clients",
      "Open Client Hub",
      "-",
      "Each client row shows '<n> visits' and '$<total spent>'",
      "P2", "Functional", "Automated", "mobile.professional.ProfessionalClientHubTest#clientsAreListed"),
    C("Client Hub", "Search", "Professional", "Mobile",
      "Clients can be searched by name",
      "Professional with several clients",
      "Type into 'Search by client name'",
      "client name",
      "Only matching clients remain listed",
      "P2", "Functional", "Automated", "mobile.professional.ProfessionalClientHubTest#searchFiltersClients"),
    C("Client Hub", "Notes", "Professional", "Mobile",
      "A private note can be added to a client and persists",
      "On a client's profile",
      "Tap '+ Add'|Enter a note|Save|Reopen the profile",
      "'prefers a #2 guard'",
      "The note persists under Notes and is not visible to the client",
      "P2", "Functional", "Manual", ""),
    C("Client Hub", "History", "Professional", "Mobile",
      "Appointment history is listed per client with prices",
      "Client with past appointments",
      "Open the client profile → 'Appointment history'",
      "-",
      "Past appointments are listed with their prices",
      "P3", "Functional", "Manual", ""),
    C("Client Hub", "Referral", "Professional", "Mobile",
      "A brought-in client is flagged with the exclusivity note",
      "Client acquired via the pro's referral link",
      "Open the client profile",
      "-",
      "'Your brought-in client — once a week until they rebook' is shown",
      "P3", "Functional", "Manual", ""),

    # ---- Earnings / payouts --------------------------------------------------
    C("Earnings", "Balance", "Professional", "Mobile",
      "The balance screen shows the withdrawable amount",
      "Professional with completed paid appointments",
      "Open the balance screen",
      "-",
      "The available balance matches the sum of released payouts; 'Refresh' re-reads it",
      "P1", "Functional", "Automated", "mobile.professional.ProfessionalEarningsTest#balanceIsShown"),
    C("Earnings", "Withdraw", "Professional", "Mobile",
      "'Withdraw all' transfers the balance to the connected account",
      "Professional with a positive balance and payouts enabled",
      "Tap 'Withdraw all'|Confirm",
      "-",
      "A payout is created, the balance drops to zero and the transaction is listed",
      "P1", "Functional", "Manual", ""),
    C("Earnings", "Withdraw", "Professional", "Mobile",
      "Withdrawing without payout onboarding is blocked",
      "Professional without a completed Stripe account",
      "Attempt to withdraw",
      "-",
      "The withdrawal is refused and the user is directed to 'Set up payouts'",
      "P1", "Negative", "Manual", ""),
    C("Earnings", "Payout account", "Professional", "Mobile",
      "Stripe payout onboarding can be started and its status refreshed",
      "Professional without payouts enabled",
      "Open 'Manage payout account'|Tap 'Set up payouts'|Complete Stripe onboarding|Tap 'Refresh status'",
      "Stripe test onboarding",
      "The onboarding link opens and, once complete, the status flips to payouts-enabled",
      "P1", "Functional", "Manual", ""),
    C("Earnings", "Transactions", "Professional", "Mobile",
      "Transaction history reconciles with appointments and tips",
      "Professional with earnings and tips",
      "Open the transactions list",
      "-",
      "Each appointment payout and tip is listed; tips are credited at 100%",
      "P1", "Functional", "Manual", ""),

    # ---- Performance / trends ------------------------------------------------
    C("Performance", "KPIs", "Professional", "Mobile",
      "KPI and performance screens load without errors",
      _PRO,
      "Open the performance screen|Open the KPI screen",
      "-",
      "Charts and metrics render; a load failure offers 'Retry'",
      "P2", "Functional", "Automated", "mobile.professional.ProfessionalPerformanceTest#performanceLoads"),
    C("Performance", "Trends", "Professional", "Mobile",
      "The trends dashboard summarises bookings and revenue for a range",
      "Professional with bookings in range",
      "Open the trends dashboard|Change the date range",
      "last 30 days",
      "'<n> bookings' and '$<revenue>' match the range; an empty range shows 'No bookings in this range yet.'",
      "P2", "Functional", "Manual", ""),
    C("Performance", "Rating", "Professional", "Mobile",
      "A professional with fewer than 3 reviews has no computed rating",
      "Professional with 2 reviews",
      "Open the reviews/rating area",
      "-",
      "'Minimum 3 reviews required to calculate rating.'",
      "P3", "Functional", "Manual", ""),

    # ---- Reviews (pro → client) ---------------------------------------------
    C("Reviews", "Flow", "Professional", "Mobile",
      "The professional review flow requires ratings and a 20-character private note",
      "Completed appointment awaiting the pro's review",
      "Open 'Leave a Review'|Submit with an empty note",
      "-",
      "'Private Note (min 20 characters)' is enforced and required sliders are validated",
      "P2", "Negative", "Manual", ""),
    C("Reviews", "Safety", "Professional", "Mobile",
      "A safety category can be reported on a client",
      "In the pro review flow",
      "Open 'Safety Category'|Select a category|Submit",
      "Harassment / Verbal / Physical / Weapons / Violence / Other",
      "'✅ Review submitted successfully!' and the safety flag reaches the admin quality queue",
      "P1", "Functional", "Manual", ""),
    C("Reviews", "Incidents", "Professional", "Mobile",
      "Access issues, arrival delay and off-platform requests are capturable",
      "In the pro review flow",
      "Report an access issue with a reason|Set an arrival delay|Answer 'Asked to go off-platform / cash?'",
      "wrong gate code / 16–30 min / Yes",
      "Each incident is recorded against the appointment for admin review",
      "P2", "Functional", "Manual", ""),

    # ---- Services & settings -------------------------------------------------
    C("Services", "Catalogue", "Professional", "Mobile",
      "A professional can enable/disable the services they offer",
      _PRO,
      "Open the professional services page|Toggle a service off|Reopen the page",
      "-",
      "The change persists and clients can no longer book the disabled service from this pro",
      "P2", "Functional", "Manual", ""),
    C("Services", "Pricing", "Professional", "Mobile",
      "Service pricing respects admin overrides",
      "An admin override exists for a service",
      "View the service price as the professional and as a client",
      "-",
      "Both surfaces show the overridden price",
      "P2", "Functional", "Manual", ""),
    C("Profile", "Business", "Professional", "Mobile",
      "Business details (e.g. 'Fresh Cuts LLC') save and display",
      "On the professional profile form",
      "Enter the business name|Save|Reopen",
      "Fresh Cuts LLC",
      "The value persists",
      "P3", "Functional", "Manual", ""),
    C("Profile", "Portfolio", "Professional", "Mobile",
      "Portfolio images can be uploaded and removed",
      "On the portfolio screen",
      "Upload an image|Remove it",
      "1 image",
      "The gallery updates and clients see the change",
      "P2", "Functional", "Manual", ""),
    C("Profile", "About", "Professional", "Mobile",
      "The About text saves and appears on the public profile",
      "On the about page",
      "Enter a bio|Tap 'Save'|View as a client",
      "bio text",
      "The bio persists and renders on the client-facing profile",
      "P3", "Functional", "Manual", ""),
    C("Training", "Materials", "Professional", "Mobile",
      "Training materials open and completion is recorded",
      "Admin published a training material",
      "Open the training tutorials|Open a video/document|Complete it",
      "-",
      "The material plays/opens and the completion count increments on the admin side",
      "P2", "Functional", "Manual", ""),
    C("Referral", "Share", "Professional", "Mobile",
      "The referral link can be copied and shared",
      _PRO,
      "Open the share sheet|Tap copy",
      "-",
      "'Link copied' and the copied link resolves to this professional's scan-to-book",
      "P3", "Functional", "Manual", ""),
    C("Notifications", "Alerts", "Professional", "Mobile",
      "Appointment notifications deep-link to the appointment detail",
      "Professional with notifications",
      "Open the notifications page|Tap an appointment notification",
      "-",
      "The relevant appointment detail screen opens",
      "P2", "Functional", "Manual", ""),
]
