"""The Store (marketplace) — client shop, professional store, vendor catalogue/orders, admin store."""

from . import C

SHEET = "05-Store-Marketplace"
PREFIX = "STR"

_SHOP = "Logged in as a client on the Shop tab"
_PROSTORE = "Logged in as an approved professional on the Store tab"

CASES = [
    # ---- Client shop ---------------------------------------------------------
    C("Client Shop", "Catalogue", "Client", "Mobile",
      "The Shop tab lists bundles and products",
      _SHOP,
      "Open the Shop tab",
      "-",
      "Bundles (with 'Save $x') and products (name, category, price) are listed under the 'Shop' app bar",
      "P1", "Functional", "Automated", "mobile.client.ClientStoreTest#shopListsProducts"),
    C("Client Shop", "Catalogue", "Client", "Mobile",
      "An empty catalogue shows the empty state",
      "No active client-visible products",
      "Open the Shop tab",
      "-",
      "'The shop is empty right now' / 'Check back soon for take-home products.'",
      "P3", "Functional", "Manual", ""),
    C("Client Shop", "Visibility", "Client", "Mobile",
      "Pro-only products are hidden from clients",
      "A product flagged 'Pro-only' is active",
      "Open the client Shop tab and search for it",
      "pro-only product",
      "The product is not listed for the client but is listed in the professional store",
      "P1", "Security", "Automated", "mobile.client.ClientStoreTest#proOnlyProductsAreHidden"),
    C("Client Shop", "Visibility", "Client", "Mobile",
      "Draft and archived products are not sellable",
      "Products in draft/archived status",
      "Look for them in the client shop",
      "-",
      "Neither appears in the catalogue and neither can be added to a cart",
      "P1", "Security", "Manual", ""),
    C("Client Shop", "Add to cart", "Client", "Mobile",
      "Adding a product confirms and increments the cart badge",
      _SHOP,
      "Tap 'Add' on a product",
      "1 product",
      "'Added “<name>” to your cart' and the cart count increments; a failure shows 'Could not add to cart'",
      "P1", "Functional", "Automated", "mobile.client.ClientStoreTest#addProductToCart"),
    C("Client Shop", "Add to cart", "Client", "Mobile",
      "Adding a bundle adds all of its items",
      "A bundle with 2+ items",
      "Tap 'Add' on a bundle",
      "bundle",
      "'Added “<bundle>” to your cart' and every bundle item is in the cart; a failure shows 'Could not add the bundle'",
      "P1", "Functional", "Automated", "mobile.client.ClientStoreTest#addBundleToCart"),
    C("Client Cart", "Contents", "Client", "Mobile",
      "The cart shows unit price, quantity, line total and subtotal",
      "Client with items in the cart",
      "Open 'Your cart'",
      "2 items",
      "'$x each', the quantity, per-line totals and a subtotal that equals their sum",
      "P1", "Functional", "Automated", "mobile.client.ClientStoreTest#cartShowsSubtotal"),
    C("Client Cart", "Quantity", "Client", "Mobile",
      "Quantity can be increased, decreased and an item removed",
      "Client with one item in the cart",
      "Increase the quantity|Decrease it|Decrease to zero / remove the item",
      "-",
      "The line total and subtotal follow each change; removing the last item shows 'Your cart is empty'",
      "P1", "Functional", "Automated", "mobile.client.ClientStoreTest#quantityCanBeChanged"),
    C("Client Cart", "Address", "Client", "Mobile",
      "Checkout requires a street and city",
      "Client with a non-empty cart",
      "Open the cart|Clear the address fields|Tap 'Continue to payment'",
      "empty street/city",
      "'Enter your street and city.' and checkout does not proceed",
      "P1", "Negative", "Automated", "mobile.client.ClientStoreTest#checkoutRequiresAddress"),
    C("Client Cart", "Checkout", "Client", "Mobile",
      "A successful checkout places the order",
      "Client with a cart and a valid card",
      "Enter the shipping address|Tap 'Continue to payment'|Complete payment|Tap 'Done'",
      "4242 4242 4242 4242",
      "'Order placed' dialog, the cart empties and the order appears under 'Your orders'",
      "P1", "Functional", "Manual", ""),
    C("Client Cart", "Checkout", "Client", "Mobile",
      "An abandoned/failed payment leaves the cart intact and creates no order",
      "Client at the payment step",
      "Cancel the payment sheet",
      "-",
      "'Payment was not completed.' — the cart still holds the items and no order exists",
      "P1", "Negative", "Manual", ""),
    C("Client Cart", "Checkout", "Client", "Mobile",
      "A backend checkout failure is surfaced verbatim",
      "Backend returns an error (e.g. out of stock)",
      "Attempt checkout",
      "-",
      "The server's error text is shown and no order/charge is created",
      "P1", "Negative", "Manual", ""),
    C("Client Cart", "Pricing", "Client", "Mobile",
      "Bundle savings are applied at checkout",
      "Cart containing a bundle",
      "Compare the subtotal with the charged total",
      "-",
      "The note 'Bundle savings apply at checkout.' holds — the charged total is the subtotal less the bundle discount",
      "P1", "Functional", "Manual", ""),
    C("Client Orders", "List", "Client", "Mobile",
      "Orders are listed with number, date, total and savings",
      "Client with at least one order",
      "Open 'Your orders'",
      "-",
      "'Order #<id>', the placed date, the total and 'You saved $x' where applicable; none shows 'No orders yet'",
      "P1", "Functional", "Automated", "mobile.client.ClientStoreTest#ordersAreListed"),
    C("Client Orders", "Detail", "Client", "Mobile",
      "Order detail shows the shipping address, per-vendor groups and fulfilment status",
      "An order with items from two vendors",
      "Open the order",
      "-",
      "'Shipping to' with the address, one group per vendor with its fulfilment label, and the totals breakdown",
      "P1", "Functional", "Manual", ""),
    C("Client Orders", "Detail", "Client", "Mobile",
      "A shipped group shows its carrier and tracking",
      "Vendor shipped one group",
      "Open the order",
      "-",
      "The group shows the shipped state with carrier and tracking number",
      "P2", "Functional", "Manual", ""),
    C("Client Orders", "Detail", "Client", "Mobile",
      "A failed order load shows an error rather than a blank sheet",
      "Order id that fails to load",
      "Open the order",
      "-",
      "'Could not load this order.'",
      "P3", "Negative", "Manual", ""),

    # ---- Professional store --------------------------------------------------
    C("Pro Store", "Catalogue", "Professional", "Mobile",
      "The professional store shows pro-only products in addition to the public catalogue",
      _PROSTORE,
      "Open the Store tab",
      "-",
      "Both public and 'Pro-only' products are listed",
      "P1", "Functional", "Automated", "mobile.professional.ProfessionalStoreTest#proStoreListsProOnlyProducts"),
    C("Pro Store", "Cart", "Professional", "Mobile",
      "Products can be added and the cart totals correctly",
      _PROSTORE,
      "Add a product|Open 'Your cart'",
      "1 product",
      "'<n> item(s)', '$x each', subtotal and 'Estimated total' are consistent; empty shows 'Your cart is empty' with 'Browse the store'",
      "P1", "Functional", "Automated", "mobile.professional.ProfessionalStoreTest#cartTotalsAreConsistent"),
    C("Pro Store", "Checkout", "Professional", "Mobile",
      "A professional can complete a store checkout",
      "Professional with a cart, address and card",
      "Enter the shipping address|'Continue to payment'|Complete payment",
      "-",
      "'Order placed' and the order is visible to the vendor as a fulfilment group",
      "P1", "Functional", "Manual", ""),
    C("Pro Store", "Shipping", "Professional", "Mobile",
      "Per-vendor shipping is explained in the cart",
      "Cart with items from two vendors",
      "Open the cart",
      "-",
      "'Shipped by <vendor>' per group and the note 'Vendors ship your order to this address.'",
      "P3", "Functional", "Manual", ""),
    C("Pro Store", "Reviews", "Professional", "Mobile",
      "Only verified purchasers can review a product",
      "Professional who has NOT bought the product",
      "Open the product|Attempt to review",
      "-",
      "'Only verified purchasers can leave a review.' and the form is unavailable",
      "P1", "Security", "Automated", "mobile.professional.ProfessionalStoreTest#onlyPurchasersCanReview"),
    C("Pro Store", "Reviews", "Professional", "Mobile",
      "A purchaser can rate a product with an optional title and comment",
      "Professional who bought the product",
      "Open the product|'Rate this product'|Set stars, title and comment|Submit",
      "5 stars",
      "The review is saved and shown; a product with none shows 'Be the first to review this product.'",
      "P2", "Functional", "Manual", ""),

    # ---- Vendor catalogue & orders (mobile + web share these screens) --------
    C("Vendor", "Catalogue", "Vendor", "Both",
      "A vendor can create a product",
      "Logged in as a vendor",
      "Open Catalog|Tap 'New product'|Enter name, slug and description|Create",
      "name + unique slug",
      "The product is created in Draft status and listed",
      "P1", "Functional", "Automated", "web.VendorPortalTest#vendorCanCreateProduct (disabled by default)"),
    C("Vendor", "Catalogue", "Vendor", "Both",
      "Name and slug are mandatory when creating a product",
      "In the new-product dialog",
      "Create with a blank name / slug",
      "-",
      "'Name *' and 'Slug *' block the create",
      "P2", "Negative", "Automated", "web.VendorPortalTest#productRequiresNameAndSlug"),
    C("Vendor", "Catalogue", "Vendor", "Both",
      "A product without a variant cannot sell",
      "A newly created product",
      "Open the product with no variant|Attempt to set it active",
      "-",
      "'Add a variant to set a price — a product needs one to sell.' is shown and it does not become sellable",
      "P1", "Negative", "Manual", ""),
    C("Vendor", "Catalogue", "Vendor", "Both",
      "A variant can be added with price, SKU, compare-at and stock",
      "On a product detail",
      "Tap 'Add' under variants|Enter the variant name and price|Save",
      "name 'Default', price 19.99",
      "The variant is saved and the product becomes sellable once active",
      "P1", "Functional", "Automated", "web.VendorPortalTest#variantCanBeAdded (disabled by default)"),
    C("Vendor", "Catalogue", "Vendor", "Both",
      "A variant can be edited and deleted",
      "Product with a variant",
      "Edit the price|Save|Delete the variant",
      "24.99",
      "The price change reflects in the storefront; deletion removes it",
      "P2", "Functional", "Manual", ""),
    C("Vendor", "Catalogue", "Vendor", "Both",
      "Images can be added, re-ordered and deleted",
      "On a product detail",
      "Tap 'Add image'|Enter an image URL and position|Save|Delete the image",
      "https://…/p.jpg, pos 1",
      "Images render in position order; 'No images yet.' when none",
      "P2", "Functional", "Manual", ""),
    C("Vendor", "Catalogue", "Vendor", "Both",
      "Status transitions Draft → Active → Archived control storefront visibility",
      "A product with a variant",
      "Set it active|Check the client shop|Archive it|Check again",
      "-",
      "Only Active products appear in the storefront",
      "P1", "Functional", "Automated", "web.VendorPortalTest#statusControlsVisibility (disabled by default)"),
    C("Vendor", "Catalogue", "Vendor", "Both",
      "'Pro-only' restricts a product to professionals",
      "A product flagged Pro-only and active",
      "Check the professional store and the client shop",
      "-",
      "Visible to professionals only",
      "P1", "Security", "Manual", ""),
    C("Vendor", "Catalogue", "Vendor", "Both",
      "Products can be searched",
      "Vendor with many products",
      "Type into 'Search products'",
      "product name",
      "Only matching products are listed",
      "P2", "Functional", "Automated", "web.VendorPortalTest#productSearchFilters"),
    C("Vendor", "Orders", "Vendor", "Both",
      "Orders are listed with their payout amount",
      "Vendor with at least one order",
      "Open Orders",
      "-",
      "'Order #<id>' with 'Payout $x'; none shows 'No orders yet'",
      "P1", "Functional", "Automated", "web.VendorPortalTest#ordersAreListed"),
    C("Vendor", "Orders", "Vendor", "Both",
      "Shipping an order requires carrier and tracking",
      "Vendor with an unshipped order group",
      "Open the order|Tap ship|Submit without carrier/tracking|Fill both and submit",
      "USPS / 9400…",
      "Empty fields are rejected; with both the group is marked shipped and the payout releases",
      "P1", "Functional", "Automated", "web.VendorPortalTest#shippingRequiresCarrierAndTracking"),
    C("Vendor", "Orders", "Vendor", "Both",
      "Order detail shows the payout after commission",
      "Vendor with an order",
      "Open the order detail",
      "-",
      "'Your payout (after commission)' equals the order total less the platform commission rate",
      "P1", "Functional", "Manual", ""),
    C("Vendor", "Orders", "Vendor", "Both",
      "An order with no shipping address yet is handled gracefully",
      "Order awaiting an address",
      "Open the order detail",
      "-",
      "'No shipping address on file for this order yet.' and shipping is not offered",
      "P3", "Negative", "Manual", ""),
    C("Vendor", "Payouts", "Vendor", "Both",
      "Payout onboarding can be started and the status refreshed",
      "Vendor without payouts enabled",
      "Tap 'Set up payouts'|Copy the link and complete Stripe onboarding|Tap 'Refresh'",
      "Stripe test onboarding",
      "'Link copied', then after onboarding 'Status refreshed' and the pill flips to 'Payouts on'",
      "P1", "Functional", "Automated", "web.VendorPortalTest#payoutSetupLinkIsIssued"),
    C("Vendor", "Store profile", "Vendor", "Both",
      "The store profile can be edited; the store name is required",
      "Logged in as a vendor",
      "Tap 'Edit store'|Clear the name and save|Enter a name, support email and logo URL|Save",
      "'Trimio Supply Co'",
      "'Store name is required' blocks the empty save; a valid save shows 'Store updated' and the header/sidebar refresh",
      "P2", "Functional", "Automated", "web.VendorPortalTest#storeProfileCanBeEdited (disabled by default)"),
    C("Vendor", "Notifications", "Vendor", "Both",
      "Vendor notifications open and order notifications deep-link",
      "Vendor with unread notifications",
      "Open the bell|Tap an order notification",
      "-",
      "The panel lists notifications, marks them read (badge clears) and the order detail opens",
      "P2", "Functional", "Manual", ""),
    C("Vendor", "Export", "Vendor", "Both",
      "Orders can be exported to CSV",
      "Vendor with orders",
      "Tap 'Export CSV'",
      "-",
      "A CSV containing the vendor's orders downloads",
      "P3", "Functional", "Manual", ""),
    C("Vendor", "Isolation", "Vendor", "Both",
      "A vendor sees only their own products and orders",
      "Two vendors with data",
      "Log in as vendor A|Inspect Catalog and Orders",
      "-",
      "Vendor B's products and orders are never visible or addressable (API included)",
      "P1", "Security", "Manual", ""),

    # ---- Vendor application --------------------------------------------------
    C("Vendor Apply", "Public form", "Guest", "Both",
      "The 'Sell on Trimio' application can be submitted",
      "On the login screen",
      "Tap 'Want to sell on Trimio? Apply to sell'|Fill the application|Tap 'Submit application'",
      "store name, email, details",
      "'Application received' and the application appears in the admin Applications queue as pending",
      "P1", "Functional", "Automated", "web.VendorApplyTest#applicationCanBeSubmitted (disabled by default)"),
    C("Vendor Apply", "Validation", "Guest", "Both",
      "Mandatory application fields are enforced",
      "On the application form",
      "Submit with required fields blank",
      "-",
      "Validation blocks the submission",
      "P2", "Negative", "Automated", "web.VendorApplyTest#requiredFieldsAreEnforced"),
    C("Vendor Apply", "Navigation", "Guest", "Both",
      "'Back to sign in' returns to the login screen",
      "On the application form",
      "Tap 'Back to sign in'",
      "-",
      "The login screen is shown",
      "P3", "Functional", "Automated", "web.VendorApplyTest#backToSignInReturns"),

    # ---- Admin store ---------------------------------------------------------
    C("Admin Store", "Vendors", "Admin", "Both",
      "Vendors are listed with status and can be searched",
      "Logged in as an admin with vendors present",
      "Open Store|Search a vendor name",
      "-",
      "Vendors list with Active/Pending/Suspended status; the search filters them",
      "P1", "Functional", "Automated", "web.AdminStoreTest#vendorsAreListedAndSearchable"),
    C("Admin Store", "Vendors", "Admin", "Both",
      "A vendor can be created with a name, slug and commission rate",
      "Logged in as an admin",
      "Tap 'New vendor'|Enter name, slug, commission|Create",
      "0.15",
      "The vendor is created; 'Commission rate (0–1, e.g. 0.15)' is validated as a fraction",
      "P1", "Functional", "Automated", "web.AdminStoreTest#vendorCanBeCreated (disabled by default)"),
    C("Admin Store", "Vendors", "Admin", "Both",
      "A vendor login can be created manually with a temporary password",
      "An existing vendor without a login",
      "Tap 'Create login'|Enter the login email and optional password|Create",
      "email + 8+ char password",
      "The credentials are shown once with a copy action and the vendor can sign in (forced password reset)",
      "P1", "Functional", "Manual", ""),
    C("Admin Store", "Vendors", "Admin", "Both",
      "A vendor can be invited by email",
      "An existing vendor with a support email",
      "Tap 'Invite vendor'|Enter the vendor email|Send invite",
      "vendor@example.com",
      "The invite email is sent with the portal URL and temporary credentials",
      "P2", "Functional", "Manual", ""),
    C("Admin Store", "Vendors", "Admin", "Both",
      "A vendor's status and commission can be edited",
      "An existing vendor",
      "Tap 'Edit vendor'|Change status to Suspended|Save",
      "-",
      "The change persists and a suspended vendor's storefront items stop selling",
      "P1", "Functional", "Manual", ""),
    C("Admin Store", "Vendors", "Admin", "Both",
      "The Stripe onboarding link and status can be managed from admin",
      "A vendor without payouts enabled",
      "Tap 'Onboarding link'|Copy it|Tap 'Refresh Stripe status'",
      "-",
      "'Copy link' copies a working Stripe link and the refreshed status is reflected",
      "P2", "Functional", "Manual", ""),
    C("Admin Store", "Applications", "Admin", "Both",
      "Pending vendor applications are listed with their applied date",
      "≥1 pending application",
      "Open Applications",
      "-",
      "Applications are listed with 'Applied <date>' and the sidebar badge matches the pending count",
      "P1", "Functional", "Automated", "web.AdminStoreTest#pendingApplicationsAreListed"),
    C("Admin Store", "Applications", "Admin", "Both",
      "'Approve & invite' creates the store plus a login",
      "A pending application",
      "Open the application|Tap 'Approve & invite'|Confirm",
      "-",
      "'Create a store + login for “<name>”' completes, credentials are issued, and an invite-email failure degrades to 'Approved — invite email failed' rather than losing the account",
      "P1", "Functional", "Manual", ""),
    C("Admin Store", "Applications", "Admin", "Both",
      "An application can be rejected with an internal note",
      "A pending application",
      "Tap 'Reject'|Add an internal note|Confirm",
      "'incomplete business details'",
      "The application moves to rejected and the note is retained internally",
      "P2", "Functional", "Manual", ""),
    C("Admin Store", "Products", "Admin", "Both",
      "Admin can create and edit any vendor's product",
      "Logged in as an admin",
      "Open Store → products|Create a product|Edit it and add a variant",
      "-",
      "The product is created/edited on the target vendor and appears in their catalogue",
      "P1", "Functional", "Automated", "web.AdminStoreTest#adminCanCreateProduct (disabled by default)"),
    C("Admin Store", "Fulfillment", "Admin", "Both",
      "Admin can mark an order group shipped with carrier and tracking",
      "An unshipped order group",
      "Open fulfillment|Search the order|Tap 'Ship'|Enter carrier and tracking|Confirm",
      "USPS / 9400…",
      "The group is marked shipped and 'Payout on ship: $x' is released to the vendor",
      "P1", "Functional", "Automated", "web.AdminStoreTest#orderCanBeMarkedShipped (disabled by default)"),
    C("Admin Store", "Payouts", "Admin", "Both",
      "Vendor transfers are listed and searchable by order",
      "Vendor payouts exist",
      "Open payouts|Search by order number",
      "order #",
      "The matching transfer is listed with its amount",
      "P2", "Functional", "Automated", "web.AdminStoreTest#payoutsAreSearchable"),
    C("Admin Store", "Auth", "Admin", "Both",
      "Store admin screens refuse a non-admin session",
      "Signed in as a non-admin (or signed out)",
      "Open a store admin screen",
      "-",
      "'Admin sign-in required' / 'Sign in with an admin account to manage the store.' and no data is returned by the API",
      "P1", "Security", "Manual", ""),
]
