"""Web portal (Flutter Web) — access control, admin console, vendor portal."""

from . import C

SHEET = "06-Web-Portal"
PREFIX = "WEB"

_PORTAL = "The Trimio portal is served (main_web.dart) and reachable at web.baseUrl"
_ADMINWEB = "Signed in to the portal as an admin"

CASES = [
    # ---- Access control (the staff-only rule) --------------------------------
    C("Access Control", "Client blocked", "Client", "Web",
      "A client cannot sign in to the web portal",
      _PORTAL + "; a valid client account exists",
      "Open the portal|Enter valid client credentials|Submit",
      "verified client account",
      "The 'Use the Trimio app' dialog explains the portal is staff only; no portal screen is reached",
      "P1", "Security", "Automated", "web.WebPortalAccessTest#clientIsBlockedFromPortal"),
    C("Access Control", "Professional blocked", "Professional", "Web",
      "A professional cannot sign in to the web portal",
      _PORTAL + "; a valid professional account exists",
      "Open the portal|Enter valid professional credentials|Submit",
      "professional account",
      "'Use the Trimio app' with the professional-specific copy about schedule/offers/earnings",
      "P1", "Security", "Automated", "web.WebPortalAccessTest#professionalIsBlockedFromPortal"),
    C("Access Control", "Session teardown", "Client", "Web",
      "A blocked login leaves no usable session behind",
      "A client login was just refused in the browser",
      "Dismiss the dialog|Reload the portal",
      "-",
      "Firebase is signed out and userId/userType/userPhone/userEmail/vendor_id are cleared, so the reload lands back on login — not on a client screen",
      "P1", "Security", "Automated", "web.WebPortalAccessTest#blockedLoginLeavesNoSession"),
    C("Access Control", "Server side", "Client", "API",
      "The backend refuses a browser login for a phone-only role",
      "Backend running with WEB_PORTAL_BLOCK_ENABLED unset (default on)",
      "POST /auth/login with an Origin header and client credentials",
      "Origin: http://localhost:8080",
      "HTTP 403 with error_code 'WEB_PORTAL_NOT_AVAILABLE' and no token issued",
      "P1", "Security", "Automated", "web.WebPortalAccessTest#backendRefusesBrowserClientLogin"),
    C("Access Control", "Server side", "Client", "API",
      "The same client credentials still work from a native client",
      "Backend running",
      "POST /auth/login with NO Origin/Sec-Fetch-Site header",
      "client credentials",
      "HTTP 200 — the block must not affect the mobile apps",
      "P1", "Security", "Automated", "web.WebPortalAccessTest#nativeClientLoginStillWorks"),
    C("Access Control", "Server side", "Client", "API",
      "Browser self-registration for a phone-only role is refused",
      "Backend running",
      "POST the registration endpoint with an Origin header and user_type_id=1",
      "-",
      "HTTP 403 WEB_PORTAL_NOT_AVAILABLE and no account is created",
      "P1", "Security", "Manual", ""),
    C("Access Control", "Server side", "Client", "API",
      "Browser OTP completion for a phone-only role is refused",
      "An OTP flow started for a client",
      "Complete the OTP from a browser context",
      "-",
      "HTTP 403 WEB_PORTAL_NOT_AVAILABLE — the block cannot be bypassed via the OTP path",
      "P1", "Security", "Manual", ""),
    C("Access Control", "Allowed roles", "Admin", "Web",
      "An admin (type 3) can sign in to the portal",
      _PORTAL + "; admin account exists",
      "Sign in as an admin",
      "-",
      "The admin WebShell opens with the sidebar and top bar",
      "P1", "Security", "Automated", "web.WebPortalAccessTest#adminCanSignIn"),
    C("Access Control", "Allowed roles", "Vendor", "Web",
      "A vendor (type 9) can sign in to the portal",
      _PORTAL + "; vendor account exists",
      "Sign in as a vendor",
      "-",
      "The vendor WebShell opens with the 'Vendor Portal' sidebar",
      "P1", "Security", "Automated", "web.WebPortalAccessTest#vendorCanSignIn"),
    C("Access Control", "Allowed roles", "Support", "Web",
      "A support user (type 4) is permitted by the portal guard",
      _PORTAL + "; support account exists",
      "Sign in as support",
      "-",
      "The login is not blocked (support is in the allowed set)",
      "P2", "Security", "Manual", ""),
    C("Access Control", "Config", "Admin", "API",
      "WEB_PORTAL_BLOCK_ENABLED=false disables the block",
      "Backend restarted with the flag false",
      "POST /auth/login with an Origin header and client credentials",
      "-",
      "The login succeeds — the switch is honoured (documented escape hatch)",
      "P3", "Configuration", "Manual", ""),
    C("Access Control", "Config", "Admin", "API",
      "WEB_PORTAL_ROLE_IDS overrides the allowed set",
      "Backend restarted with WEB_PORTAL_ROLE_IDS='3'",
      "Attempt a vendor browser login",
      "-",
      "The vendor is now refused, proving the list is honoured",
      "P3", "Configuration", "Manual", ""),

    # ---- Portal shell --------------------------------------------------------
    C("Shell", "Sidebar", "Admin", "Web",
      "The admin sidebar renders every destination in its groups",
      _ADMINWEB,
      "Inspect the sidebar",
      "-",
      "OVERVIEW: Dashboard · MANAGE: All Users, Services, Quality Control, Reports, Price Overrides, Enforcements, Training · MARKETPLACE: Store, Applications · Countries & States",
      "P1", "Functional", "Automated", "web.AdminPortalNavigationTest#sidebarShowsAllDestinations"),
    C("Shell", "Sidebar", "Admin", "Web",
      "Selecting a destination swaps the content and updates the top-bar title",
      _ADMINWEB,
      "Click each sidebar destination in turn",
      "-",
      "The content area swaps in place (chrome stays put) and the top bar shows the destination label",
      "P1", "Functional", "Automated", "web.AdminPortalNavigationTest#everyDestinationOpens"),
    C("Shell", "Sidebar", "Admin", "Web",
      "Destinations keep their state when revisited",
      _ADMINWEB,
      "Open All Users|Scroll/filter|Open Reports|Return to All Users",
      "-",
      "The cached screen is restored rather than rebuilt from scratch",
      "P3", "Functional", "Manual", ""),
    C("Shell", "Badges", "Admin", "Web",
      "Sidebar badges show attention counts and neutral counts",
      "Unread notifications and open reports exist",
      "Inspect All Users, Reports, Store, Applications, Services",
      "-",
      "Red badges show attention counts (users+moderation, open reports, store, pending applications); Services/All Users show a neutral total when there is nothing to action",
      "P2", "Functional", "Automated", "web.AdminPortalNavigationTest#sidebarBadgesReflectCounts"),
    C("Shell", "Responsive", "Admin", "Web",
      "Below 900px the sidebar collapses into a drawer",
      _ADMINWEB,
      "Resize the viewport to 800px wide|Open the hamburger menu|Pick a destination",
      "800x800",
      "The sidebar becomes a drawer, the menu button appears and picking a destination closes the drawer",
      "P2", "Compatibility", "Automated", "web.AdminPortalNavigationTest#sidebarCollapsesOnNarrowViewport"),
    C("Shell", "Top bar", "Admin", "Web",
      "The notification bell opens the notification centre and shows the unread count",
      "Admin with unread notifications",
      "Click the bell",
      "-",
      "The badge matches the unread count and the notification centre opens",
      "P2", "Functional", "Automated", "web.AdminPortalNavigationTest#bellOpensNotifications"),
    C("Shell", "Top bar", "Admin", "Web",
      "The account menu logs the admin out",
      _ADMINWEB,
      "Open the avatar menu|Choose 'Log out'",
      "-",
      "The session ends and the login screen is shown; reloading does not restore it",
      "P1", "Security", "Automated", "web.AdminPortalNavigationTest#accountMenuLogsOut"),
    C("Shell", "Footer", "Admin", "Web",
      "The sidebar footer identifies the signed-in principal",
      _ADMINWEB,
      "Inspect the sidebar footer",
      "-",
      "'Administrator' / 'Signed in' for admins; the store name and 'Payouts on/off' for vendors",
      "P3", "Functional", "Manual", ""),

    # ---- Admin web dashboard -------------------------------------------------
    C("Dashboard", "KPIs", "Admin", "Web",
      "The dashboard shows four KPI cards with correct values",
      _ADMINWEB,
      "Open the Dashboard destination",
      "-",
      "Total users (with the clients/pros split), Active holds, Open reports and Services match the underlying data",
      "P1", "Functional", "Automated", "web.AdminPortalNavigationTest#dashboardShowsKpis"),
    C("Dashboard", "Greeting", "Admin", "Web",
      "The dashboard greets by time of day with today's date",
      _ADMINWEB,
      "Open the Dashboard",
      "-",
      "'Good morning/afternoon/evening, Admin' and the full date followed by '· everything at a glance'",
      "P3", "Functional", "Manual", ""),
    C("Dashboard", "Attention", "Admin", "Web",
      "'Needs attention' and 'all caught up' render for the right states",
      "Once with unread notifications, once with none",
      "Open the Dashboard in both states",
      "-",
      "'<n> item(s) need attention' with a category summary, or \"You're all caught up\"",
      "P2", "Functional", "Automated", "web.AdminPortalNavigationTest#attentionOrAllClearIsShown"),
    C("Dashboard", "Manage grid", "Admin", "Web",
      "Each management tile navigates to its destination",
      _ADMINWEB,
      "Click each tile in the Manage grid",
      "-",
      "The sidebar selection and content follow the tile (users, services, quality, reports, pricing, enforce, training, store, states)",
      "P1", "Functional", "Automated", "web.AdminPortalNavigationTest#manageTilesNavigate"),
    C("Dashboard", "Recent activity", "Admin", "Web",
      "'Latest events' lists recent notifications with category pills and relative times",
      "Recent admin notifications exist",
      "Open the Dashboard|Inspect 'Recent activity'|Click a row",
      "-",
      "Up to 6 events with a category pill and 'just now / Nm ago / Nh ago / Nd ago'; clicking deep-links to the queue. Empty shows 'No recent activity'",
      "P2", "Functional", "Automated", "web.AdminPortalNavigationTest#recentActivityIsListed"),
    C("Dashboard", "Responsive", "Admin", "Web",
      "The KPI row and manage grid reflow across breakpoints",
      _ADMINWEB,
      "View at 1440px, 900px and 600px",
      "-",
      "Columns reflow (4/2/1 for KPIs, 4/3/2 for tiles) with no horizontal scrolling or clipped text",
      "P2", "Compatibility", "Automated", "web.AdminPortalNavigationTest#dashboardIsResponsive"),

    # ---- Admin screens embedded in the portal --------------------------------
    C("Admin Screens", "All Users", "Admin", "Web",
      "All Users renders inside the portal with the correct client/pro counts",
      _ADMINWEB,
      "Open All Users",
      "-",
      "The embedded screen renders full-width and its counts match the dashboard KPI",
      "P1", "Functional", "Automated", "web.AdminPortalNavigationTest#everyDestinationOpens"),
    C("Admin Screens", "Quality", "Admin", "Web",
      "Quality control actions work from the browser",
      _ADMINWEB,
      "Open Quality Control|Search a user|Suspend and reinstate them",
      "-",
      "The same behaviour as the mobile console, including the mandatory reason",
      "P1", "Functional", "Manual", ""),
    C("Admin Screens", "Reports", "Admin", "Web",
      "The reports queue and detail work from the browser",
      _ADMINWEB,
      "Open Reports|Open a report|Resolve it",
      "-",
      "The status updates and the badge count drops",
      "P1", "Functional", "Manual", ""),
    C("Admin Screens", "Price Overrides", "Admin", "Web",
      "Overrides can be created and deleted from the browser",
      _ADMINWEB,
      "Open Price Overrides|Create an override|Delete it",
      "-",
      "Both operations behave as on mobile",
      "P2", "Functional", "Manual", ""),
    C("Admin Screens", "Regions", "Admin", "Web",
      "Countries & States renders and states can be approved",
      _ADMINWEB,
      "Open Countries & States|Open a state|Approve it",
      "-",
      "The state becomes active",
      "P2", "Functional", "Manual", ""),
    C("Admin Screens", "Training", "Admin", "Web",
      "Training materials can be managed from the browser",
      _ADMINWEB,
      "Open Training|Create a material|Delete it",
      "-",
      "Both operations behave as on mobile",
      "P3", "Functional", "Manual", ""),

    # ---- Vendor portal -------------------------------------------------------
    C("Vendor Portal", "Shell", "Vendor", "Web",
      "The vendor sidebar shows the four store destinations",
      "Signed in to the portal as a vendor",
      "Inspect the sidebar",
      "-",
      "MY STORE: Overview, Catalog, Orders, Payouts — and no admin destinations",
      "P1", "Security", "Automated", "web.VendorPortalTest#vendorSidebarShowsStoreDestinations"),
    C("Vendor Portal", "Header", "Vendor", "Web",
      "The store header shows identity, product count, fee and payout status",
      "Signed in as a vendor",
      "Inspect the header strip above the content",
      "-",
      "Store name, '<n> products · <x>% platform fee' and a pill reading 'Payouts on' / 'Onboarding' / 'No payouts'",
      "P1", "Functional", "Automated", "web.VendorPortalTest#storeHeaderShowsContext"),
    C("Vendor Portal", "Header", "Vendor", "Web",
      "The payout CTA reflects the onboarding state",
      "Vendor without payouts enabled, once with and once without a Stripe account",
      "Inspect the CTA",
      "-",
      "'Set up payouts' with no account, 'Continue payout setup' + 'Refresh' once an account exists, and no CTA once payouts are on",
      "P2", "Functional", "Automated", "web.VendorPortalTest#payoutCtaReflectsState"),
    C("Vendor Portal", "Overview", "Vendor", "Web",
      "The overview surfaces the to-ship metric and links to Orders",
      "Vendor with unshipped orders",
      "Open Overview|Follow the to-ship link",
      "-",
      "The to-ship count matches the Orders badge and the link switches to the Orders destination",
      "P2", "Functional", "Automated", "web.VendorPortalTest#overviewLinksToOrders"),
    C("Vendor Portal", "Isolation", "Vendor", "Web",
      "A vendor cannot reach admin destinations by URL or by API",
      "Signed in as a vendor",
      "Attempt to call a /store/admin endpoint with the vendor session",
      "-",
      "The request is refused; no admin data is returned",
      "P1", "Security", "Manual", ""),

    # ---- Web platform behaviour ---------------------------------------------
    C("Platform", "Semantics", "Any", "Web",
      "The portal exposes an accessibility tree that assistive tech (and automation) can read",
      _PORTAL,
      "Load the portal|Enable accessibility|Inspect the DOM",
      "-",
      "flt-semantics nodes carry aria-labels for the sidebar, top bar and content controls",
      "P2", "Accessibility", "Automated", "WebBasePage#enableSemantics (used by every web test)"),
    C("Platform", "Reload", "Admin", "Web",
      "Reloading the portal preserves the signed-in session",
      _ADMINWEB,
      "Reload the page",
      "-",
      "The user stays signed in and lands on the shell (not the login screen)",
      "P2", "Functional", "Manual", ""),
    C("Platform", "Deep state", "Admin", "Web",
      "Browser back does not corrupt the shell",
      _ADMINWEB,
      "Navigate through several destinations|Press browser Back",
      "-",
      "The app remains usable — no blank content area or lost sidebar",
      "P3", "Functional", "Manual", ""),
    C("Platform", "Browsers", "Admin", "Web",
      "The portal works on Chromium, Firefox and WebKit",
      _PORTAL,
      "Run the portal smoke suite on each engine",
      "-browser=chromium|firefox|webkit",
      "Login, sidebar navigation and one data screen work on all three",
      "P2", "Compatibility", "Automated", "web-testng.xml (browser parameter)"),
    C("Platform", "CORS", "Any", "Web",
      "The portal reaches the API without disabling web security",
      "Backend configured with the portal origin allowed",
      "Load the portal and sign in",
      "-",
      "No CORS errors in the console — the documented --disable-web-security workaround is not needed in a deployed environment",
      "P2", "Configuration", "Manual", ""),
    C("Platform", "Errors", "Any", "Web",
      "The browser console is free of uncaught errors during the smoke path",
      _PORTAL,
      "Sign in and visit every destination while recording console output",
      "-",
      "No uncaught exceptions or failed asset/API requests",
      "P2", "Reliability", "Manual", ""),
]
